---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gitlab-webservice
  namespace: gitlab
spec:
  secretName: tls-gitlab-webservice
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - gitlab.spack.io

  # Set the renewal very close to the expiration date as a last resort. The policy for renewing
  # spack-gitlab certificates is to do so manually, as a regeneration of the OIDC thumbprint
  # (via terraform apply) is required.
  # Certificate renewals that don't coincide with a regeneration of the OIDC thumbprint will result
  # in a broken OIDC configuration for all jobs.
  renewBefore: 48h
