version: '3.7'
services:
  web-server:
    image: scottwittenburg/pr-binary-graduation:0.0.1
    command: --redis-host rq-server --redis-port 6379 --work-queue workload --web-server-host 0.0.0.0 --web-server-port 80
    ports:
      - 8080:80

  rq-worker:
    image: scottwittenburg/pr-binary-graduation:0.0.1
    entrypoint: rq worker -u redis://rq-server:6379 --with-scheduler workload
    deploy:
      replicas: 2

  rq-server:
    image: redis:alpine
    expose:
      - 6379
    volumes:
      - redis-data:/data
      - redis-conf:/usr/local/etc/redis/redis.conf

volumes:
  redis-data:
  redis-conf:
