---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitlab-api-scrape
  namespace: custom
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::588562868276:role/PutObjectInPipelineStatistics
