images:
  - path: ./images/gh-gl-sync
    image: ghcr.io/spack/ci-bridge:0.0.47

  - path: ./images/ci-key-clear
    image: ghcr.io/spack/ci-key-clear:0.0.3

  - path: ./images/gitlab-stuckpods
    image: ghcr.io/spack/stuckpods:0.0.2

  - path: ./images/gitlab-clear-pipelines
    image: ghcr.io/spack/gitlab-clear-pipelines:0.0.1

  - path: ./images/gitlab-delete-stale-branches
    image: ghcr.io/spack/gitlab-delete-stale-branches:0.0.1

  - path: ./images/gitlab-skipped-pipelines
    image: ghcr.io/spack/gitlab-skipped-pipelines:0.0.3

  - path: ./images/notary
    image: ghcr.io/spack/notary:0.0.4

  - path: ./images/python-aws-bash
    image: ghcr.io/spack/python-aws-bash:0.0.2

  - path: ./images/cache-indexer
    image: ghcr.io/spack/cache-indexer:0.0.6

  - path: ./analytics
    image: ghcr.io/spack/django:0.5.20

  - path: ./images/ci-prune-buildcache
    image: ghcr.io/spack/ci-prune-buildcache:0.0.5

  - path: ./images/buildcache-tools
    image: ghcr.io/spack/buildcache-tools:0.0.1

  - path: ./images/retry-trigger-jobs
    image: ghcr.io/spack/retry-trigger-jobs:0.0.2

  - path: ./images/runner-node-certificate-controller
    image: ghcr.io/spack/runner-node-certificate-controller:0.0.2
