set(CTEST_SITE "GitHub Actions")
set(CTEST_BUILD_NAME "$ENV{GITHUB_WORKFLOW} $ENV{GITHUB_RUN_ID}")
set(CTEST_SOURCE_DIRECTORY ${CTEST_SCRIPT_DIRECTORY}/../gh-gl-sync)
set(CTEST_BINARY_DIRECTORY ${CTEST_SCRIPT_DIRECTORY}/../gh-gl-sync/bin)
set(CTEST_CMAKE_GENERATOR "Unix Makefiles")
set(CTEST_UPDATE_COMMAND "git")
set(CTEST_UPDATE_VERSION_ONLY 1)

ctest_empty_binary_directory("${CTEST_BINARY_DIRECTORY}")
ctest_start(Experimental)
ctest_update()
ctest_configure()
ctest_test()
ctest_coverage()
ctest_submit()
