---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spackbotdev-spack-io
  namespace: spack
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::588562868276:role/FullCRUDAccessToBucketSpackBinariesPRs
