---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sentry
  namespace: sentry
spec:
  secretName: tls-sentry
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - sentry.staging.spack.io
