---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: sentry
  namespace: sentry
spec:
  interval: 10m
  url: https://sentry-kubernetes.github.io/charts

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sentry
  namespace: sentry
spec:
  interval: 10m
  chart:
    spec:
      chart: sentry
      version: 20.0.0
      sourceRef:
        kind: HelmRepository
        name: sentry

  values:
    user:
      create: true
      email: sentry@spack.io
      password: "g&UKkRsLu2ZR^*TEF^#d&CMrERFP2*onSens&UUtErJUz#cJ2bZ*34mZa&75HNv2"

    ingress:
      enabled: true

      annotations:
        kubernetes.io/ingress.class: nginx

      hostname: sentry.staging.spack.io

      tls:
      - secretName: tls-sentry
        hosts: [sentry.staging.spack.io]

    vroom:
      nodeSelector: {}
    relay:
      nodeSelector: {}
    sentry:
      web:
        nodeSelector: {}
      worker:
        nodeSelector: {}
      ingestConsumer:
        nodeSelector: {}
      ingestMetricsConsumerPerf:
        nodeSelector: {}
      ingestMetricsConsumerRh:
        nodeSelector: {}
      ingestReplayRecordings:
        nodeSelector: {}
      ingestProfiles:
        nodeSelector: {}
      ingestMonitors:
        nodeSelector: {}
      billingMetricsConsumer:
        nodeSelector: {}
      cron:
        nodeSelector: {}
      subscriptionConsumerEvents:
        nodeSelector: {}
      subscriptionConsumerSessions:
        nodeSelector: {}
      subscriptionConsumerTransactions:
        nodeSelector: {}
      postProcessForwardErrors:
        nodeSelector: {}
      postProcessForwardTransactions:
        nodeSelector: {}

    snuba:
      api:
        nodeSelector: {}
      consumer:
        nodeSelector: {}
      outcomesConsumer:
        nodeSelector: {}
      replacer:
        nodeSelector: {}
      subscriptionConsumerEvents:
        nodeSelector: {}
      subscriptionConsumerTransactions:
        nodeSelector: {}
      subscriptionConsumerSessions:
        nodeSelector: {}
      replaysConsumer:
        nodeSelector: {}
      sessionsConsumer:
        nodeSelector: {}
      transactionsConsumer:
        nodeSelector: {}
      profilingProfilesConsumer:
        nodeSelector: {}
      profilingFunctionsConsumer:
        nodeSelector: {}

---
# apiVersion: helm.toolkit.fluxcd.io/v2beta1
# kind: HelmRelease
# metadata:
#   name: sentry-kubernetes
#   namespace: sentry
# spec:
#   interval: 10m
#   chart:
#     spec:
#       chart: sentry-kubernetes
#       version: 0.3.2
#       sourceRef:
#         kind: HelmRepository
#         name: sentry

#   values:
#     sentry:
#       dsn: https://31968f1eeb484ab9b371e76a5f232f06@sentry.staging.spack.io/2
