---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: webhook-handler
  namespace: custom

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: webhook-handler
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "watch", "list"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: webhook-handler
subjects:
  - kind: ServiceAccount
    name: webhook-handler
    namespace: custom
roleRef:
  kind: ClusterRole
  name: webhook-handler
  apiGroup: rbac.authorization.k8s.io
