---
apiVersion: v1
kind: Service
metadata:
  name: webhook-handler
  namespace: custom
  labels:
    app: webhook-handler
    svc: web
spec:
  type: ClusterIP
  ports:
    - name: web
      port: 80
      targetPort: 8080
  selector:
    app: webhook-handler
    svc: web
