{
 "title": "Build Timing Dashboard",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "5m",
 "panels": [
  { "title": "Phase Timings", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Non-Cache Stage Timings by Package",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "WITH T as (\n    SELECT\n        analytics_job.package_name as package_name,\n        analytics_timerphase.name as name,\n        SUM(analytics_timerphase.seconds) as total\n    FROM analytics_timerphase\n    LEFT JOIN analytics_timer ON analytics_timerphase.timer_id = analytics_timer.id\n    LEFT JOIN analytics_job ON analytics_timer.job_id = analytics_job.job_id\n    WHERE\n        $__timeFilter(analytics_job.started_at)\n        AND analytics_timer.cache IS FALSE\n    GROUP BY\n        analytics_job.package_name,\n        analytics_timerphase.name\n    ORDER BY analytics_job.package_name\n)\n\nSELECT\n    package_name,\n    SUM(total) filter (WHERE T.name = 'autoreconf') as autoreconf,\n    SUM(total) filter (WHERE T.name = 'bootstrap') as bootstrap,\n    SUM(total) filter (WHERE T.name = 'build') as build,\n    SUM(total) filter (WHERE T.name = 'cmake') as cmake,\n    SUM(total) filter (WHERE T.name = 'configure') as configure,\n    SUM(total) filter (WHERE T.name = 'edit') as edit,\n    SUM(total) filter (WHERE T.name = 'generate_luarocks_config') as generate_luarocks_config,\n    SUM(total) filter (WHERE T.name = 'hostconfig') as hostconfig,\n    SUM(total) filter (WHERE T.name = 'initconfig') as initconfig,\n    SUM(total) filter (WHERE T.name = 'install') as install,\n    SUM(total) filter (WHERE T.name = 'meson') as meson,\n    SUM(total) filter (WHERE T.name = 'post-install') as post_install,\n    SUM(total) filter (WHERE T.name = 'preprocess') as preprocess,\n    SUM(total) filter (WHERE T.name = 'qmake') as qmake,\n    SUM(total) filter (WHERE T.name = 'stage') as stage,\n    SUM(total) as stages_total\nFROM T\nGROUP BY T.package_name\nORDER BY stages_total DESC\nLIMIT 20\n;"
    }
   ]
  },
  {
   "title": "Build Duration By Package with Percentages",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH T as (\n    SELECT\n        ROW_NUMBER() OVER (ORDER BY total_sum DESC) as id,\n        name,\n        total_sum\n    FROM (\n        SELECT\n            analytics_timer.name as name,\n            sum(time_total) as total_sum\n            FROM analytics_timer\n            LEFT JOIN analytics_job on analytics_timer.job_id = analytics_job.job_id\n            WHERE $__timeFilter(analytics_job.started_at)\n            GROUP BY analytics_timer.name\n    ) s\n    GROUP BY s.name, s.total_sum\n    ORDER BY s.total_sum DESC\n)\n\n\n-- Select top N, and then sum remaining into \"other\" category\n(\n    SELECT name, total_sum FROM T WHERE id <= 20\n) UNION (\n    SELECT 'other' as name, SUM(total_sum) as total_sum FROM T WHERE id > 20\n)\n\nORDER BY total_sum DESC\n\n;"
    }
   ]
  },
  {
   "title": "Cache Stage Timings by Package",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "WITH T as (\n    SELECT\n        analytics_job.package_name as package_name,\n        analytics_timerphase.name as name,\n        SUM(analytics_timerphase.seconds) as total\n    FROM analytics_timerphase\n    LEFT JOIN analytics_timer ON analytics_timerphase.timer_id = analytics_timer.id\n    LEFT JOIN analytics_job ON analytics_timer.job_id = analytics_job.job_id\n    WHERE\n        -- analytics_job.started_at >= CAST((CAST(now() AS timestamp) + (INTERVAL '-7 day')) AS date)\n        $__timeFilter(analytics_job.started_at)\n        AND analytics_timer.cache IS TRUE\n    GROUP BY\n        analytics_job.package_name,\n        analytics_timerphase.name\n    ORDER BY analytics_job.package_name\n)\n\nSELECT\n    package_name,\n    SUM(total) filter (WHERE T.name = 'extract') as extract,\n    SUM(total) filter (WHERE T.name = 'fetch') as fetch,\n    SUM(total) filter (WHERE T.name = 'install') as install,\n    SUM(total) filter (WHERE T.name = 'relocate') as relocate,\n    SUM(total) filter (WHERE T.name = 'search') as search,\n    SUM(total) as stages_total\nFROM T\nGROUP BY T.package_name\nORDER BY stages_total DESC\nLIMIT 20\n;"
    }
   ]
  },
  {
   "title": "Time by Stage",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT name, SUM(seconds) as seconds from analytics_timerphase\n  WHERE is_subphase = false\nGROUP BY name\nORDER BY seconds DESC\n;"
    }
   ]
  },
  { "title": "Cache Timings", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Cache vs. Non-Cache Build Times by Package",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 17, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "WITH\npackage_total_table AS (\n    SELECT\n        analytics_job.package_name,\n        analytics_timer.cache,\n        SUM(analytics_timer.time_total) as total\n    FROM analytics_timer\n    INNER JOIN analytics_job ON analytics_timer.job_id = analytics_job.job_id\n    WHERE $__timeFilter(analytics_job.started_at) \n    GROUP BY\n        analytics_job.package_name,\n        analytics_timer.cache\n    ORDER BY total DESC\n)\n\nSELECT\n    cache_true_t.package_name,\n    -- Do SUM here so that there's no GROUP BY needed on these two fields\n    SUM(cache_false_t.total) as cache_false,\n    SUM(cache_true_t.total) as cache_true,\n    SUM(cache_false_t.total) + SUM(cache_true_t.total) as absolute_total\nFROM (\n    SELECT package_name, total\n    FROM package_total_table\n    WHERE package_total_table.cache is TRUE\n) cache_true_t\nLEFT JOIN (\n    SELECT package_name, total\n    FROM package_total_table\n    WHERE package_total_table.cache is FALSE\n) cache_false_t\nON cache_true_t.package_name = cache_false_t.package_name\nGROUP BY\n    cache_true_t.package_name\nORDER BY\n    absolute_total DESC\nLIMIT 20\n;"
    }
   ]
  },
  {
   "title": "Fetch from cache times (summary)",
   "type": "piechart",
   "gridPos": { "h": 16, "w": 7, "x": 17, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(\"public\".\"analytics_timerphase\".\"seconds\") / (COUNT(*) * 1.0) AS \"seconds\", \"public\".\"analytics_job\".\"ref\" as \"ref_name\"\nFROM \"public\".\"analytics_timerphase\"\nJOIN \"public\".\"analytics_timer\" ON \"public\".\"analytics_timerphase\".\"timer_id\" = \"public\".\"analytics_timer\".\"id\"\nJOIN \"public\".\"analytics_job\" ON \"public\".\"analytics_timer\".\"job_id\" = \"public\".\"analytics_job\".\"job_id\"\nWHERE\n  \"public\".\"analytics_timer\".\"cache\" IS true\n  AND \"public\".\"analytics_timerphase\".\"name\" LIKE 'fetch'\n  -- AND \"public\".\"analytics_job\".\"project_id\" = 23\n  AND \"public\".\"analytics_job\".\"ref\" LIKE '%ci-refactor-mirror-usage%'\nGROUP BY \"ref_name\""
    }
   ]
  },
  {
   "title": "Avg per-pkg fetch from cache time",
   "type": "barchart",
   "gridPos": { "h": 16, "w": 17, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT AVG(\"public\".\"analytics_timerphase\".\"seconds\") AS \"avg time\", COUNT(*) as \"count\", \"public\".\"analytics_timer\".\"name\" as \"package\", \"public\".\"analytics_job\".\"ref\" as \"ref\"\nFROM \"public\".\"analytics_timerphase\"\nJOIN \"public\".\"analytics_timer\" ON \"public\".\"analytics_timerphase\".\"timer_id\" = \"public\".\"analytics_timer\".\"id\"\nJOIN \"public\".\"analytics_job\" ON \"public\".\"analytics_timer\".\"job_id\" = \"public\".\"analytics_job\".\"job_id\"\nWHERE\n  \"public\".\"analytics_timer\".\"cache\" IS true\n  AND \"public\".\"analytics_timerphase\".\"name\" LIKE 'fetch'\n  -- AND \"public\".\"analytics_job\".\"project_id\" = 23\n  AND \"public\".\"analytics_job\".\"ref\" LIKE '%ci-refactor-mirror-usage%'\nGROUP BY \"public\".\"analytics_timer\".\"name\", \"ref\"\nORDER BY \"avg time\" DESC\nLIMIT 20\n;"
    }
   ]
  }
 ]
}