{
 "title": "Cost Per Job Metrics",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  { "title": "Cost Per Job", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Top 20 most expensive packages by average cost per job",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 18, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT\n    package_name,\n    AVG(node_occupancy * (EXTRACT(epoch from duration)) * (instance_type_spot_price / 3600)) as job_cost\nFROM\n  \"public\".\"core_jobpod\"\nINNER JOIN \"public\".\"core_job\" AS \"core_job\" ON \"public\".\"core_jobpod\".\"id\" = \"core_job\".\"pod_id\"\nINNER JOIN \"public\".\"core_node\" AS \"core_node - node_id\" ON \"core_job\".\"node_id\" = \"core_node - node_id\".\"id\"\nWHERE $__timeFilter(started_at)\nGROUP BY package_name\nORDER BY job_cost DESC\nLIMIT 20\n;"
    }
   ]
  },
  {
   "title": "Most Expensive Packages in Total",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    package_name,\n    SUM(node_occupancy * (EXTRACT(epoch from duration)) * (instance_type_spot_price / 3600)) as job_cost\nFROM\n  \"public\".\"core_jobpod\"\nINNER JOIN \"public\".\"core_job\" AS \"core_job\" ON \"public\".\"core_jobpod\".\"id\" = \"core_job\".\"pod_id\"\nINNER JOIN \"public\".\"core_node\" AS \"core_node - node_id\" ON \"core_job\".\"node_id\" = \"core_node - node_id\".\"id\"\nWHERE $__timeFilter(started_at)\nGROUP BY package_name\nORDER BY job_cost DESC\nLIMIT 10\n;"
    }
   ]
  },
  { "title": "Memory Limit Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Lowest Memory \"High Water Mark\" (percentage of memory limit)",
   "type": "barchart",
   "description": "Packages that have excessively low numbers here should have their memory limit decreased",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "WITH T as (\n  SELECT\n      package_name,\n      AVG(max_mem::float / memory_limit::float) as max_memory_util\n  FROM core_job\n  INNER JOIN core_jobpod ON core_job.pod_id = core_jobpod.id\n  WHERE\n    $__timeFilter(started_at)\n  GROUP BY package_name\n)\n\nSELECT\n    package_name,\n    max_memory_util\nFROM T\nORDER BY max_memory_util ASC\nLIMIT 10\n;"
    }
   ]
  },
  {
   "title": "Highest Memory \"High Water Mark\" (percentage of memory limit)",
   "type": "barchart",
   "description": "Packages that have excessively high numbers here should have their memory limit increased",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "WITH T as (\n  SELECT\n      package_name,\n      AVG(max_mem::float / memory_limit::float) as max_memory_util\n  FROM core_job\n  INNER JOIN core_jobpod ON core_job.pod_id = core_jobpod.id\n  WHERE\n    $__timeFilter(started_at)\n  GROUP BY package_name\n)\n\nSELECT\n    package_name,\n    max_memory_util\nFROM T\nORDER BY max_memory_util DESC\nLIMIT 10\n;"
    }
   ]
  },
  { "title": "Memory Request Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Lowest Average Memory Utilization (percentage of request)",
   "type": "barchart",
   "description": "Packages that have excessively low numbers here should have their memory request decreased",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "WITH T as (\n  SELECT\n      package_name,\n      AVG(avg_mem::float / memory_request::float) as avg_memory_util\n  FROM core_job\n  INNER JOIN core_jobpod ON core_job.pod_id = core_jobpod.id\n  WHERE\n    $__timeFilter(started_at)\n  GROUP BY package_name\n)\n\nSELECT\n    package_name,\n    avg_memory_util\nFROM T\nORDER BY avg_memory_util ASC\nLIMIT 10\n;"
    }
   ]
  },
  {
   "title": "Highest Average Memory Utilization (percentage of memory request)",
   "type": "barchart",
   "description": "Packages that have numbers excessively higher than 100% should have their memory request increased",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "WITH T as (\n  SELECT\n      package_name,\n      AVG(avg_mem::float / memory_request::float) as avg_memory_util\n  FROM core_job\n  INNER JOIN core_jobpod ON core_job.pod_id = core_jobpod.id\n  WHERE\n    $__timeFilter(started_at)\n  GROUP BY package_name\n)\n\nSELECT\n    package_name,\n    avg_memory_util\nFROM T\nWHERE\n  avg_memory_util > 1\nORDER BY avg_memory_util DESC\nLIMIT 20\n;"
    }
   ]
  }
 ]
}