{
 "title": "Build Timing Dashboard",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Avg per-pkg install from cache time",
   "type": "barchart",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT AVG(\"public\".\"analytics_timerphase\".\"seconds\") AS \"avg time\", COUNT(*) as \"count\", \"public\".\"analytics_timer\".\"name\" as \"package\", \"public\".\"analytics_job\".\"ref\" as \"ref\"\nFROM \"public\".\"analytics_timerphase\"\nJOIN \"public\".\"analytics_timer\" ON \"public\".\"analytics_timerphase\".\"timer_id\" = \"public\".\"analytics_timer\".\"id\"\nJOIN \"public\".\"analytics_job\" ON \"public\".\"analytics_timer\".\"job_id\" = \"public\".\"analytics_job\".\"job_id\"\nWHERE \"public\".\"analytics_timer\".\"cache\" IS true AND \"public\".\"analytics_timerphase\".\"name\" LIKE 'fetch'\nGROUP BY \"public\".\"analytics_timer\".\"name\", \"ref\"\nORDER BY \"package\", \"avg time\" DESC"
    }
   ]
  },
  {
   "title": "Fetch from cache times (experimental)",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 6, "x": 9, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(\"public\".\"analytics_timerphase\".\"seconds\") / (COUNT(*) * 1.0) AS \"seconds\", \"public\".\"analytics_job\".\"ref\" as \"ref_name\"\nFROM \"public\".\"analytics_timerphase\"\nJOIN \"public\".\"analytics_timer\" ON \"public\".\"analytics_timerphase\".\"timer_id\" = \"public\".\"analytics_timer\".\"id\"\nJOIN \"public\".\"analytics_job\" ON \"public\".\"analytics_timer\".\"job_id\" = \"public\".\"analytics_job\".\"job_id\"\nWHERE \"public\".\"analytics_timer\".\"cache\" IS true AND \"public\".\"analytics_timerphase\".\"name\" LIKE 'fetch'\nGROUP BY \"ref_name\""
    }
   ]
  },
  {
   "title": "Average Job Duration by Package Name",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 6, "x": 6, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT package_name, AVG(duration) from analytics_job\n  GROUP BY package_name\n  ORDER BY avg DESC\nLIMIT 100\n;"
    }
   ]
  },
  {
   "title": "Average Timer Duration by Package",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 6, "x": 12, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT name, cache, AVG(time_total) as time_total from analytics_timer\nGROUP BY name, cache\nORDER BY time_total DESC\nLIMIT 100\n;"
    }
   ]
  },
  {
   "title": "Average Time by Top-Level Phase",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 6, "x": 6, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT name, AVG(seconds) as seconds from analytics_timerphase\n  WHERE is_subphase = false\nGROUP BY name\nORDER BY seconds DESC\n;"
    }
   ]
  },
  {
   "title": "Average Time by Sub-Phase",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 6, "x": 12, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT name, AVG(seconds) as seconds from analytics_timerphase\n  WHERE is_subphase = true\nGROUP BY name\nORDER BY seconds DESC\n;"
    }
   ]
  }
 ]
}