{
 "title": "Pipeline User Impact",
 "tags": [ "production" ],
 "time": { "from": "now-7d", "to": "now-6h" },
 "panels": [
  {
   "title": "Top Packages by Total Build Time",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    (regexp_matches(name, '^\\(specs\\) ([^/]+)\\/.+'))[1] as package_name,\n    EXTRACT(epoch FROM SUM(finished_at - started_at)) as duration\n    -- SUM(finished_at - started_at) as duration\nFROM ci_builds\nWHERE\n    \"finished_at\" BETWEEN '2023-03-29T21:23:44.96Z' AND '2023-04-05T15:23:44.96Z'\n    AND name LIKE '(specs)%'\n    AND finished_at IS NOT NULL AND started_at IS NOT NULL\nGROUP BY package_name\nORDER BY duration DESC\n-- LIMIT 10\n;"
    }
   ]
  },
  {
   "title": "Top 10 Packages by CPU build time",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (label_metrics_spack_job_spec_pkg_name) (\n    rate(container_cpu_usage_seconds_total{namespace=\"pipeline\", container=\"build\"}[$__rate_interval])\n    * on(pod) group_left(\n        label_metrics_gitlab_ci_pipeline_id,\n        label_metrics_gitlab_ci_job_stage,\n        label_metrics_gitlab_ci_commit_ref_name,\n        label_metrics_spack_ci_stack_name,\n        label_metrics_spack_job_spec_pkg_name\n    )\n    kube_pod_labels{namespace=\"pipeline\", label_metrics_spack_job_spec_pkg_name!=\"\"}\n)",
     "legendFormat": "{{label_metrics_spack_job_spec_pkg_name}}"
    }
   ]
  },
  {
   "title": "Top 5 errors by day",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" },
      {
       "field": "error_taxonomy.keyword",
       "id": "3",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_count", "size": "5" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Pipelines Status (success vs. failed)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "rawSql": "SELECT $__timeGroup(finished_at, $__interval) as time, COUNT(*) as failed from ci_pipelines\nLEFT JOIN ci_sources_pipelines ON ci_sources_pipelines.pipeline_id = ci_pipelines.id\nWHERE\n  $__timeFilter(\"finished_at\")\n  AND ci_sources_pipelines.source_job_id IS NULL\n  AND status = 'failed'\n  GROUP BY time\n;",
     "timeField": "timestamp"
    },
    {
     "rawSql": "SELECT $__timeGroup(finished_at, '6h') as time, COUNT(*) as success from ci_pipelines\nLEFT JOIN ci_sources_pipelines ON ci_sources_pipelines.pipeline_id = ci_pipelines.id\nWHERE\n  $__timeFilter(\"finished_at\")\n  AND ci_sources_pipelines.source_job_id IS NULL\n  AND status = 'success'\n  GROUP BY time\n;"
    }
   ]
  }
 ]
}