{
 "title": "Pipeline / Overview",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Quick Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Node Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_labels{label_spack_io_pipeline=\"true\"})",
     "legendFormat": "Instance"
    }
   ]
  },
  {
   "title": "CPU Total Utilization",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(\n(kube_node_labels{label_spack_io_pipeline=\"true\"} * on(node) group_left(internal_ip) kube_node_info) * on(internal_ip) group_left label_replace(100 * sum by(instance) (sum without (cpu)(irate(node_cpu_seconds_total{mode!=\"idle\"}[3m])) / ignoring(mode) group_left sum without(mode, cpu) (irate(node_cpu_seconds_total[3m]))), 'internal_ip', '$1', 'instance', '(.+):.+'))"
    }
   ]
  },
  {
   "title": "RAM Total Utilization",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(kube_node_info * on(internal_ip) group_right(node) label_replace(((node_memory_MemTotal_bytes - node_memory_MemFree_bytes) / node_memory_MemTotal_bytes) * 100, 'internal_ip', '$1', 'instance', '(.+):.+') and on(internal_ip) (kube_node_labels{label_spack_io_node_pool=~\"glr.*\"} * on(node) group_left(internal_ip) kube_node_info))"
    }
   ]
  },
  {
   "title": "Pod Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_info{namespace=\"pipeline\"})",
     "legendFormat": "Pods"
    }
   ]
  },
  {
   "title": "Pipeline Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum by(label_metrics_gitlab_ci_commit_ref_name) (kube_pod_info{namespace=\"pipeline\"} * on(pod) group_left(label_metrics_gitlab_ci_commit_ref_name) kube_pod_labels{namespace=\"pipeline\"}))"
    }
   ]
  },
  {
   "title": "Pod number by Pipeline",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(label_metrics_gitlab_ci_commit_ref_name) (kube_pod_info{namespace=\"pipeline\"} * on(pod) group_left(label_metrics_gitlab_ci_commit_ref_name) kube_pod_labels{namespace=\"pipeline\"})",
     "legendFormat": "{{ label_metrics_gitlab_ci_commit_ref_name }}"
    }
   ]
  },
  {
   "title": "CPU Total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_labels{label_spack_io_pipeline=\"true\"} * on(node) group_left() kube_node_status_capacity{resource=\"cpu\"})",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(kube_node_labels{label_spack_io_pipeline=\"true\"} * on(node) group_left(internal_ip) kube_node_info) * on(internal_ip) group_left label_replace(100 * sum by(instance) (sum without (cpu)(irate(node_cpu_seconds_total{mode!=\"idle\"}[3m])) / ignoring(mode) group_left sum without(mode, cpu) (irate(node_cpu_seconds_total[3m]))), 'internal_ip', '$1', 'instance', '(.+):.+')",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum((label_replace(node_memory_MemTotal_bytes, 'internal_ip', '$1', 'instance', '(.+):.+') and on(internal_ip) kube_node_labels{label_spack_io_node_pool=~\"glr.*\"} * on(node) group_left(internal_ip) kube_node_info))",
     "legendFormat": "Bytes"
    }
   ]
  },
  {
   "title": "RAM Utilization",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(kube_node_labels{label_spack_io_pipeline=\"true\"} * on(node) group_left(internal_ip) kube_node_info) * on(internal_ip) group_left label_replace(((node_memory_MemTotal_bytes - node_memory_MemFree_bytes) / node_memory_MemTotal_bytes) * 100, 'internal_ip', '$1', 'instance', '(.+):.+') ",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Pod count per CI Ref",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum by(label_metrics_gitlab_ci_commit_ref_name) (kube_pod_labels{namespace=\"pipeline\"})",
     "legendFormat": "{{label_metrics_gitlab_ci_commit_ref_name}}"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Utilization",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "avg(label_replace(node_uname_info, \"node\", '$1', 'nodename', \"(.*)\") * on(node) group_right(instance) kube_node_labels{label_spack_io_pipeline=\"true\"} * on(instance) (((node_memory_MemTotal_bytes - node_memory_MemFree_bytes) / node_memory_MemTotal_bytes) * 100))\n\n",
     "legendFormat": "RAM"
    },
    {
     "expr": "avg(label_replace(node_uname_info, \"node\", '$1', 'nodename', \"(.*)\") * on(node) group_right(instance) kube_node_labels{label_spack_io_pipeline=\"true\"}  * on(instance) (100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"node-exporter\",mode=\"idle\"}[1m])) * 100)))\n",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Node Count  by Type",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "sum by(label_node_kubernetes_io_instance_type) (kube_node_labels{label_spack_io_node_pool=~\"glr-.*\"})",
     "legendFormat": "{{label_beta_kubernetes_io_instance_type}}"
    }
   ]
  },
  {
   "title": "Avg Pods per Instance Type",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "avg by(label_beta_kubernetes_io_instance_type) (kube_node_labels{label_spack_io_node_pool=~\"glr.*\"} * on(node) group_left() sum by(node) (kube_pod_info{namespace=\"pipeline\", node!=\"\"}))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Testing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 },
   "collapsed": true,
   "targets": [
    {}
   ]
  }
 ]
}