---
# Provisioner for graviton2 gitlab runners
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: glr-graviton2
spec:
  providerRef:
    name: default

  # Terminate nodes after 5 minutes of idle time
  ttlSecondsAfterEmpty: 300

  # Taint these nodes so only pipeline pods will be scheduled on them.
  taints:
    - key: spack.io/runner-taint
      value: "true"
      effect: NoSchedule

  # Resource limits for this provisioner only
  limits:
    resources:
      cpu: 3840 # 16 vCPUs * 6 replicas * 20 concurrent jobs * 2 runners (public & protected)
      memory: 15Ti # 64 Gi * 6 replicas * 20 concurrent jobs * 2 runners (public & protected)

  requirements:
    # Only spin up arm64 nodes
    - key: "kubernetes.io/arch"
      operator: In
      values: ["arm64"]

    # Instance Size
    - key: "karpenter.k8s.aws/instance-size"
      operator: In
      values:
        - "medium"
        - "large"
        - "xlarge"
        - "2xlarge"
        - "3xlarge"
        - "4xlarge"
        - "6xlarge"
        - "8xlarge"
        - "10xlarge"
        - "12xlarge"
        - "16xlarge"

    # Availability Zones
    - key: "topology.kubernetes.io/zone"
      operator: In
      values:
        - "us-east-1a"
        - "us-east-1b"
        - "us-east-1c"
        - "us-east-1d"

    # Only use spot instances for runners
    - key: "karpenter.sh/capacity-type"
      operator: In
      values: ["spot"]

  # Label all provisioned nodes as graviton 2
  labels:
    spack.io/pipeline: "true"
    spack.io/graviton: "2"
