# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: event-exporter-cfg
#   namespace: monitoring
#   annotations:
#     kustomize.toolkit.fluxcd.io/reconcile: disabled
# type: Opaque
# stringData:
#   config.yaml: |
#     kubeQPS: 3 # 1/5 of Burst
#     kubeBurst: 15 # estimate of events per minute
#     maxEventAgeSeconds: 60
#     logLevel: error
#     logFormat: json
#     route:
#       # Main route
#       routes:
#         # This route allows dumping all events because it has no fields to match and no drop rules.
#         - match:
#             - receiver: "runner-events"
#             - namespace: "pipeline|gitlab"
#     receivers:
#       - name: "runner-events"
#         opensearch:
#           hosts:
#             - DEADBEEF
#           index: kube-events
#           indexFormat: "kube-events-{2006-01-02}"
#           username: USER
#           password: PASSWORD
#           # If set to true, it allows updating the same document in ES (might be useful handling count)
#           useEventID: false
#           deDot: true
