apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../production/custom/runner-node-certificate-controller/cron-jobs.yaml
  - ../../../production/custom/runner-node-certificate-controller/service-accounts.yaml
