# Generated by Django 4.2.4 on 2023-08-17 17:57

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "job_id",
                    models.PositiveBigIntegerField(primary_key=True, serialize=False),
                ),
                ("project_id", models.PositiveBigIntegerField()),
                ("name", models.CharField(max_length=128)),
                ("started_at", models.DateTimeField()),
                ("duration", models.FloatField()),
                ("ref", models.CharField(max_length=256)),
                (
                    "tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=32),
                        default=list,
                        size=None,
                    ),
                ),
                ("package_name", models.CharField(max_length=128)),
                ("aws", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Timer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("time_total", models.FloatField()),
                ("hash", models.CharField(max_length=128, null=True)),
                ("cache", models.BooleanField(null=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timers",
                        to="analytics.job",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Phase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("path", models.CharField(max_length=128)),
                ("seconds", models.FloatField()),
                ("count", models.PositiveIntegerField()),
                (
                    "timer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phases",
                        to="analytics.timer",
                    ),
                ),
            ],
        ),
    ]
