# Generated by Django 4.2.4 on 2023-11-09 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0003_job_arch_job_build_jobs_job_compiler_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ErrorTaxonomy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("attempt_number", models.PositiveSmallIntegerField()),
                ("retried", models.BooleanField()),
                ("error_taxonomy", models.CharField(max_length=64)),
                ("error_taxonomy_version", models.CharField(max_length=32)),
                (
                    "webhook_payload",
                    models.JSONField(
                        help_text="The JSON payload received from the GitLab job webhook."
                    ),
                ),
                (
                    "job",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="error_taxonomy",
                        to="analytics.job",
                    ),
                ),
            ],
        ),
    ]
