# Generated by Django 4.2.4 on 2023-11-09 19:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0004_errortaxonomy"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="job_cpu_request",
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="job_memory_request",
            field=models.PositiveBigIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="node_capacity_type",
            field=models.CharField(
                choices=[("spot", "Spot"), ("on-demand", "On Demand")],
                default=None,
                max_length=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="node_cpu",
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="node_instance_type",
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="node_instance_type_spot_price",
            field=models.FloatField(
                default=None,
                help_text="The price per hour (in USD) of the spot instnce this job ran on, at the time of running. If ever the job runs on an on-demand node, this field will be null.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="node_mem",
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="node_name",
            field=models.CharField(default=None, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="node_uid",
            field=models.UUIDField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="duration",
            field=models.FloatField(null=True),
        ),
        migrations.AddConstraint(
            model_name="job",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("aws__isnull", True),
                        ("job_cpu_request__isnull", True),
                        ("job_memory_request__isnull", True),
                        ("node_capacity_type__isnull", True),
                        ("node_cpu__isnull", True),
                        ("node_instance_type__isnull", True),
                        ("node_instance_type_spot_price__isnull", True),
                        ("node_mem__isnull", True),
                        ("node_name__isnull", True),
                        ("node_uid__isnull", True),
                    ),
                    models.Q(
                        ("aws__isnull", False),
                        ("job_cpu_request__isnull", False),
                        ("job_memory_request__isnull", False),
                        ("node_capacity_type__isnull", False),
                        ("node_cpu__isnull", False),
                        ("node_instance_type__isnull", False),
                        ("node_instance_type_spot_price__isnull", False),
                        ("node_mem__isnull", False),
                        ("node_name__isnull", False),
                        ("node_uid__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="aws-consistent-null-data",
            ),
        ),
    ]
