# Generated by Django 4.2.4 on 2023-12-08 19:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0004_errortaxonomy"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="job_cpu_request",
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="job_memory_request",
            field=models.PositiveBigIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="node_capacity_type",
            field=models.CharField(
                choices=[("spot", "Spot"), ("on-demand", "On Demand")],
                default=None,
                max_length=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="node_cpu",
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="node_instance_type",
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="node_instance_type_spot_price",
            field=models.FloatField(
                default=None,
                help_text="The price per hour (in USD) of the spot instnce this job ran on,"
                " at the time of running. If ever the job runs on an on-demand node,"
                " this field will be null.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="node_mem",
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="node_name",
            field=models.CharField(default=None, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="node_uid",
            field=models.UUIDField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="duration",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="tags",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=32),
                default=None,
                null=True,
                size=None,
            ),
        ),
        migrations.AddConstraint(
            model_name="job",
            constraint=models.UniqueConstraint(
                fields=("project_id", "job_id"), name="unique-project-job-id"
            ),
        ),
        migrations.AddConstraint(
            model_name="job",
            constraint=models.CheckConstraint(
                check=models.Q(("package_name", ""), _negated=True),
                name="non-empty-package-name",
            ),
        ),
        migrations.AddConstraint(
            model_name="job",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("duration__isnull", True), ("tags__isnull", True)),
                    models.Q(("duration__isnull", False), ("tags__isnull", False)),
                    _connector="OR",
                ),
                name="consistent-temporary-null-values",
            ),
        ),
    ]
