# Generated by Django 4.2.4 on 2024-01-15 17:44
from datetime import timedelta

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import functions


def transfer_duration(apps, schema_editor):
    Job = apps.get_model("analytics", "Job")
    Job.objects.all().update(
        new_duration=functions.Cast(
            functions.Concat(models.F("duration"), models.Value(" seconds")),
            output_field=models.DurationField(),
        )
    )


def remove_null_aws(apps, schema_editor):
    Job = apps.get_model("analytics", "Job")
    Job.objects.filter(aws__isnull=True).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0005_alter_job_aws"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobPod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("node_occupancy", models.FloatField()),
                ("cpu_usage_seconds", models.FloatField()),
                ("max_mem", models.PositiveBigIntegerField()),
                ("avg_mem", models.PositiveBigIntegerField()),
                ("cpu_request", models.FloatField(default=None, null=True)),
                ("cpu_limit", models.FloatField(default=None, null=True)),
                (
                    "memory_request",
                    models.PositiveBigIntegerField(default=None, null=True),
                ),
                (
                    "memory_limit",
                    models.PositiveBigIntegerField(default=None, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Node",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default=None, max_length=64, null=True)),
                ("system_uuid", models.UUIDField(default=None, null=True)),
                ("cpu", models.PositiveIntegerField(default=None, null=True)),
                ("memory", models.PositiveIntegerField(default=None, null=True)),
                (
                    "capacity_type",
                    models.CharField(
                        choices=[("spot", "Spot"), ("on-demand", "On Demand")],
                        default=None,
                        max_length=12,
                        null=True,
                    ),
                ),
                (
                    "instance_type",
                    models.CharField(default=None, max_length=32, null=True),
                ),
                (
                    "instance_type_spot_price",
                    models.FloatField(
                        default=None,
                        help_text="The price per hour (in USD) of the spot instnce this job ran on, at the time of running. If ever the job runs on an on-demand node, this field will be null.",
                        null=True,
                    ),
                ),
            ],
        ),
        # Remove any instances of a `null` aws field before making it non-nullable
        migrations.RunPython(remove_null_aws),
        migrations.AlterField(
            model_name="job",
            name="aws",
            field=models.BooleanField(default=True),
        ),
        # 1. Add the new_duration field, that stores an interval type
        # 2. Cast the original data in durations from a float (representing seconds) to an interval
        # 3. Delete the old duration float field
        # 4. Rename the new_duration field to duration
        migrations.AddField(
            model_name="job",
            name="new_duration",
            field=models.DurationField(default=timedelta),
            preserve_default=False,
        ),
        migrations.RunPython(transfer_duration),
        migrations.RemoveField(
            model_name="job",
            name="duration",
        ),
        migrations.RenameField(
            model_name="job",
            old_name="new_duration",
            new_name="duration",
        ),
        # Continue with normal migration steps
        migrations.AddConstraint(
            model_name="job",
            constraint=models.UniqueConstraint(
                fields=("project_id", "job_id"), name="unique-project-job-id"
            ),
        ),
        migrations.AddConstraint(
            model_name="job",
            constraint=models.CheckConstraint(
                check=models.Q(("package_name", ""), _negated=True),
                name="non-empty-package-name",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="node",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="jobs",
                to="analytics.node",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="pod",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="analytics.jobpod",
            ),
        ),
        migrations.AddConstraint(
            model_name="job",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("aws", False), ("node__isnull", True)),
                    models.Q(("aws", True), ("node__isnull", False)),
                    _connector="OR",
                ),
                name="aws-node-presence",
            ),
        ),
        migrations.AddConstraint(
            model_name="job",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("aws", False), ("pod__isnull", True)),
                    models.Q(("aws", True), ("pod__isnull", False)),
                    _connector="OR",
                ),
                name="aws-pod-presence",
            ),
        ),
        migrations.AddConstraint(
            model_name="node",
            constraint=models.UniqueConstraint(
                fields=("name", "system_uuid"), name="unique-name-system-uuid"
            ),
        ),
    ]
