---
apiVersion: v1
kind: Secret
metadata:
  name: spack-build-credentials
  namespace: spack
  annotations:
    fluxcd.io/ignore: "true"
  labels:
    app: builds-spack-io
    svc: web
data:
  social_auth_github_key: |
    # result of:
    echo -n ${social_auth_github_key} | base64
  social_auth_github_secret: |
    # result of:
    echo -n ${social_auth_github_secret} | base64
  database_host: |
    # result of:
    echo -n database_host | base64    
  database_name: |
    # result of:
    echo -n database_name | base64    
  database_password: |
    # result of:
    echo -n database_password | base64    
  database_user: |
    # result of:
    echo -n database_user | base64
