---
apiVersion: v1
kind: Service
metadata:
  name: operator
  namespace: kube-system
  annotations:
    operator.min.io/authors: MinIO, Inc.
    operator.min.io/license: AGPLv3
    operator.min.io/support: https://subnet.min.io
  labels:
    name: minio-operator
spec:
  ports:
  - name: https
    port: 4222
  - name: http
    port: 4221
  selector:
    name: minio-operator
    operator: leader
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: console
  namespace: kube-system
  annotations:
    operator.min.io/authors: MinIO, Inc.
    operator.min.io/license: AGPLv3
    operator.min.io/support: https://subnet.min.io
  labels:
    name: console
spec:
  ports:
  - name: http
    port: 9090
  - name: https
    port: 9443
  selector:
    app: console
