---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: gitlab-setting-updater
  namespace: gitlab
spec:
  schedule: "0 * * * *"
  # Only save the most recent run to avoid overpopulating the pod list in the gitlab namespace
  successfulJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      labels:
        app: gitlab-setting-updater
    spec:
      template:
        metadata:
          name: gitlab-setting-updater
          namespace: gitlab
          labels:
            app: gitlab-setting-updater
        spec:
          serviceAccountName: gitlab-setting-updater
          restartPolicy: OnFailure
          containers:
            - name: updater
              image: bitnami/kubectl
              imagePullPolicy: IfNotPresent
              command: ["kubectl"]
              args:
                [
                  "exec",
                  "-i",
                  "deploy/gitlab-toolbox",
                  "-c",
                  "toolbox",
                  "--",
                  "/srv/gitlab/bin/rails",
                  "runner",
                  "ApplicationSetting.update(max_yaml_size_bytes: 20.megabytes)",
                ]
          nodeSelector:
            spack.io/node-pool: base
