---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitlab-setting-updater
  namespace: gitlab
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitlab-setting-updater
  namespace: gitlab
rules:
  - apiGroups: ["", "extensions", "apps"]
    resources: ["deployments", "replicasets", "pods", "pods/exec"]
    verbs: ["get", "watch", "list", "update", "create", "patch", "delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitlab-setting-updater
  namespace: gitlab
subjects:
  - kind: ServiceAccount
    name: gitlab-setting-updater
roleRef:
  kind: Role
  name: gitlab-setting-updater
  apiGroup: rbac.authorization.k8s.io
