---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prometheus
  namespace: monitoring
spec:
  secretName: tls-prometheus-webservice
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - prometheus.spack.io

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana
  namespace: monitoring
spec:
  secretName: tls-grafana-webservice
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - grafana.spack.io

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: alertmanager
  namespace: monitoring
spec:
  secretName: tls-alertmanager-webservice
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - alertmanager.spack.io
