---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: runner-large-arm-prot
  namespace: gitlab
spec:
  releaseName: large-arm-prot
  chart:
    name: gitlab-runner
    repository: https://charts.gitlab.io
    version: 0.37.2  # gitlab-runner@14.7.0
  values:
    image: gitlab/gitlab-runner:alpine-v14.7.0
    imagePullPolicy: IfNotPresent
    replicas: 3

    gitlabUrl: "https://gitlab.spack.io/"
    unregisterRunners: true
    terminationGracePeriodSeconds: 21600  # six hours
    concurrent: 20
    checkInterval: 30
    # preEntrypointScript: |
    #   echo "Hello, from large-prot runner"

    metrics:
      enabled: true

    rbac:
      serviceAccountName: runner

    runners:
      config: |
        [[runners]]
          output_limit = 4096
          environment = ["FF_GITLAB_REGISTRY_HELPER_IMAGE=1"]
          [runners.kubernetes]
            helper_image = "gitlab/gitlab-runner-helper:arm-latest"
            privileged = false

            cpu_request = "750m"
            cpu_request_overwrite_max_allowed = "16"
            cpu_limit = "16"
            cpu_limit_overwrite_max_allowed = "16"

            memory_request = "2G"
            memory_request_overwrite_max_allowed = "64G"
            memory_limit = "64G"
            memory_limit_overwrite_max_allowed = "64G"

            namespace = "pipeline"
            poll_timeout = 600  # ten minutes
            service_account = "spack-binaries-develop-mirror"  # gives write access to protected develop mirror
            [runners.kubernetes.pod_annotations]
              "fluentbit.io/exclude" = "true"
              "gitlab/ci_pipeline_url" = "$CI_PIPELINE_URL"
              "gitlab/ci_job_url" = "$CI_JOB_URL"
              "gitlab/ci_project_url" = "$CI_PROJECT_URL"
              "gitlab/ci_runner_description" = "$CI_RUNNER_DESCRIPTION"
              "gitlab/ci_job_id" = "$CI_JOB_ID"
            [runners.kubernetes.pod_labels]
              "gitlab/ci_job_size" = "$CI_JOB_SIZE"
              "metrics/gitlab_ci_pipeline_id" = "$CI_PIPELINE_ID"
              "metrics/gitlab_ci_project_namespace" = "$CI_PROJECT_NAMESPACE"
              "metrics/gitlab_ci_project_name" = "$CI_PROJECT_NAME"
              "metrics/gitlab_ci_job_stage" = "$CI_JOB_STAGE"
              "metrics/gitlab_ci_commit_ref_name" = "$CI_COMMIT_REF_NAME"
              "metrics/spack_ci_stack_name" = "$SPACK_CI_STACK_NAME"
              "metrics/spack_job_spec_pkg_name" = "$SPACK_JOB_SPEC_PKG_NAME"
              "metrics/spack_spec_needs_rebuild" = "$SPACK_SPEC_NEEDS_REBUILD"
            [runners.kubernetes.node_selector]
              "kubernetes.io/arch" = "arm64"
              "spack.io/node-pool" = "glr-large-pub"

            [[runners.kubernetes.volumes.secret]]
              name = "spack-intermediate-ci-signing-key"
              mount_path = "/mnt/key/"
              read_only = true


      # default image
      image: "busybox:1.32.0"
      imagePullPolicy: "if-not-present"

      locked: true
      protected: true
      runUntagged: false

      tags: "arm,aarch64,graviton,graviton2,small,medium,large,huge,protected,aws,spack"
      secret: spack-project-runner-registration-token

      # Distributed runners caching
      # TODO(opadron): Look into this after setting up stand-alone minio service
      cache: {}
        ## General settings
        # cacheType: s3
        # cachePath: "gitlab_runner"
        # cacheShared: true

        ## S3 settings
        # s3ServerAddress: s3.amazonaws.com
        # s3BucketName:
        # s3BucketLocation:
        # s3CacheInsecure: false
        # secretName: s3access

        ## GCS settings
        # gcsBucketName:
        ## Use this line for access using access-id and private-key
        # secretName: gcsaccess
        ## Use this line for access using google-application-credentials file
        # secretName: google-application-credentials

      services: {}
      # cpuRequests: 50m
      # cpuLimit: 50m
      # memoryRequests: 144Mi
      # memoryLimit: 144Mi

    nodeSelector:
      spack.io/node-pool: base  # pool for the runner
