apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../production/secrets-backup/service-accounts.yaml
patches:
  - target:
      kind: ServiceAccount
      name: secrets-backup
      namespace: custom
    patch: |-
      - op: replace
        path: /metadata/annotations/eks.amazonaws.com~1role-arn
        value: arn:aws:iam::588562868276:role/SecretsBackupRole-staging
