apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cdash-extra
  namespace: cdash
spec:
  encryptedData:
    APP_PREVIOUS_KEYS: 
      AgAacAYHLSam+yqnVw+m4rELhrmSZ5hxCFzwyJ6gcR+j+U3GzjsXC+ukn3oDP35S2bt6nlAVtiKUxOcLIdroDLYzb6nP0h5RaLG3NgnXd4lX2IUeZDe8KAekL3woUMsmbOx9G52yIiVKRXBDNbTp6nW1v7eJWBz0f+HPPAvqet00cmhDAqNjmVPa08JyDPlJsPKJmbTa1AQX1taO4kqa6sAwEg69BTEQEQfY6vh+2dPM0X2+Qchnr1Xv473suXEgvFRwv7JSIS4Iw2T64gtfEwT0WmmBZ0LyVhD7iLVbAUGIPmHuXbGBKEKkHcYuvLwrRjtV9WHU8YGTsF77NBfQ9XoSwgwbqwOwhmnZjl68WmBi/mGh7ZScCclajRBzKfg+lktne8v24cWX2tLvbCxgCpKuTPOjpxHEG4A0HC7MWcsl/ht9+Y/mY6W/s9NdLQ/pWcbxUXRMAStqKun9qp8GSHU+EjqE7RQ3Vf0eX3DRfEgcjpNcrOioiRjrMyVLZ5Jx+VQE6LU1uZa0QVKopTdBgLh/TGwv4hqYYsM8uXyQ8xBy/YHD4gsAnlbxQwhHQpGrsm0b8rE6sy6fvhVAR7039bA9PgpgH5l8FZWsAVE+eDUtsvQYyw4XO0I190vUtOIizNJYC4yBaoxRVvZo5LXJKLczW/MP2UNfq9n4tCpLuvSr2jbGUX8mWjYUsgoPJ9D63qTIaowhpg2ZzSCmJeNe1lVrkImNqE/vTU8cPatZgEPLTg==
  template:
    metadata:
      annotations:
        kustomize.toolkit.fluxcd.io/reconcile: disabled
        sealedsecrets.bitnami.com/managed: "true"
