apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cdash-extra
  namespace: cdash
spec:
  encryptedData:
    APP_PREVIOUS_KEYS: 
      AgCSsaNSnPlxiELGgnRxgzN4iTrL7R6WOt8WZ5DlKOrx7s2c4FGZ5WJ5T47wG9dhVvOwALJVcBsmT9YShQ/0zuUcrEf2d2t7XRq2OXfm36yiCqgZ0zNGu9haK5KLP+SAjEDq6YdzH3IhmFNgnBxyAvc4iGv9B78+xBsfsco3LoMOJ73IT37gUMqSJ4AVFq6xzYsfrqfhXSTP+6PAoVbOeNVvSL4smCkLrenaPQSxQQ7InSqBzhMPB7cTZB2wSLREhUtlK66+o4YYMgIziOCyZKTE7PYeiSpenWKUSWd0ZNUgFXSAHKgOwowwGXow85JGjWUzGNVtdcfTma5C7aQEcfPv1ssEsytbU4vdtAholPYdTAeclBhaPwNuVodA+ox+imiwUo4uDm5QeNIInnRbVV39MnLS/SZRMXEm/A3QEcF9XUlojZ8FsvdQZnTGelfkgGjNs50QX9a0X1XOOsevNwtNFnH+MV7er7Ef84oKuaWTMo1ehupb9b5fXnRI3EtVOGZHPPhzQxAFLxlsMlZAyTOz/RHegTe3j5H+jj9WxZUqNjUbJXSV75vm5Yfvzasqj2cdCYkSdvMieIVi82ENzBz16eNpm89FQ772fkAmDylhxkRo3jM5/ogE8q3j8KoyIYSi3LWi19J9DAjxOKcQQhz1dWxBFs2vvavnUtseE3/vfsOxQgmXqU99BJgKnpT+bSZNIU0Wr7piR2n+gLb+f1stcXBdYfhUs7104uOITUe5pw==
  template:
    metadata:
      annotations:
        kustomize.toolkit.fluxcd.io/reconcile: disabled
        sealedsecrets.bitnami.com/managed: "true"
