---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cdash-updater
  namespace: cdash

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cdash-updater
  namespace: cdash
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["deployments", "replicasets", "pods", "pods/exec"]
  verbs: ["get", "watch", "list", "update", "create", "patch", "delete"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cdash-updater
  namespace: cdash
subjects:
- kind: ServiceAccount
  name: cdash-updater
roleRef:
  kind: Role
  name: cdash-updater
  apiGroup: rbac.authorization.k8s.io
