---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 10m
  url: https://charts.jetstack.io

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 10m
  chart:
    spec:
      chart: cert-manager
      version: v1.10.1
      sourceRef:
        kind: HelmRepository
        name: cert-manager
  values:
    installCRDs: false
    replicaCount: 3
    nodeSelector:
      spack.io/node-pool: base

    resources:
      requests:
        cpu: 50m
        memory: 300M

    extraArgs:
      - --enable-certificate-owner-ref=true

    prometheus:
      # TODO(opadron): enable this after installing the prometheus operator
      enabled: false

    webhook:
      replicaCount: 3
      resources:
        requests:
          cpu: 300m
          memory: 50M
      nodeSelector:
        spack.io/node-pool: base

    cainjector:
      enabled: true
      replicaCount: 3
      requests:
          cpu: 30m
          memory: 200M
      nodeSelector:
        spack.io/node-pool: base
