apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../production/cert-manager/namespace.yaml
- ../../production/cert-manager/release.yaml
- ../../production/cert-manager/crds.yaml
- ../../production/cert-manager/issuers/letsencrypt-staging.yaml
- ../../production/cert-manager/issuers/letsencrypt.yaml
patches:
  - target:
      kind: HelmRelease
      name: cert-manager
      namespace: cert-manager
    patch: |-
      - op: replace
        path: /spec/values/replicaCount
        value: 1
      - op: replace
        path: /spec/values/webhook/replicaCount
        value: 1
      - op: replace
        path: /spec/values/cainjector/replicaCount
        value: 1
