---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-packages
  namespace: spack
spec:
  secretName: tls-packages
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
  - packages.spack.io
