---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spack-packages
  namespace: spack
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - secretName: tls-packages
  rules:
  - host: packages.spack.io
    http:
      paths:
      - backend:
          service:
            name: spack-packages
            port:
              number: 80
        path: /
        pathType: ImplementationSpecific
