---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spack-packages-updater
  namespace: spack

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: spack-packages-updater
  namespace: spack
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["deployments", "replicasets", "pods", "pods/exec"]
  verbs: ["get", "watch", "list", "update", "create", "patch", "delete"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: spack-packages-updater
  namespace: spack
subjects:
- kind: ServiceAccount
  name: spack-packages-updater
roleRef:
  kind: Role
  name: spack-packages-updater
  apiGroup: rbac.authorization.k8s.io
