---
# Provisioner for x86_64_v3 gitlab runners
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: glr-x86-64-v3
spec:
  template:
    metadata:
      # Label all provisioned nodes as x86-64-v3
      labels:
        spack.io/pipeline: "true"
        spack.io/x86_64: "v3" # highest supported x86_64 microarch version

    spec:
      requirements:
      # Only spin up amd64 nodes
      - key: "kubernetes.io/arch"
        operator: In
        values: ["amd64"]

      # Only provision nodes from certain instance families that have been verified
      # to support x86_64_v3 by archspec.
      - key: "karpenter.k8s.aws/instance-family"
        operator: In
        values:
          - "c4"
          - "c5"
          - "c5a"
          - "c5n"
          - "c6a"
          - "c6i"
          - "m4"
          - "m5"
          - "m5a"
          - "m5n"
          - "m5zn"
          - "m6a"
          - "m6i"
          - "r4"
          - "r5"
          - "r5a"
          - "r5b"
          - "r5n"
          - "r6a"
          - "r6i"
          - "t2"
          - "t3"
          - "t3a"
          - "x1e"
          - "x2iedn"
          - "x2iezn"

      # Instance Size
      - key: "karpenter.k8s.aws/instance-size"
        operator: In
        values:
          - "medium"
          - "large"
          - "xlarge"
          - "2xlarge"
          - "3xlarge"
          - "4xlarge"
          - "6xlarge"
          - "8xlarge"
          - "10xlarge"
          - "12xlarge"
          - "16xlarge"

      # Availability Zones
      - key: "topology.kubernetes.io/zone"
        operator: In
        values:
          - "us-east-1a"
          - "us-east-1b"
          - "us-east-1c"
          - "us-east-1d"

      # Only provision nodes for Linux pods
      # Needed due to https://github.com/kubernetes-sigs/karpenter/issues/1009
      - key: "kubernetes.io/os"
        operator: In
        values: ["linux"]

      # Only use spot instances for runners
      - key: "karpenter.sh/capacity-type"
        operator: In
        values: ["spot"]

      nodeClassRef:
        apiVersion: karpenter.k8s.aws/v1beta1
        kind: EC2NodeClass
        name: default

      # Taint these nodes so only pipeline pods will be scheduled on them.
      taints:
        - key: spack.io/runner-taint
          value: "true"
          effect: NoSchedule

  # Terminate nodes after 5 minutes of idle time
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 5m

  # Resource limits for this provisioner only
  limits:
    cpu: 3840 # 16 vCPUs * 6 replicas * 20 concurrent jobs * 2 runners (public & protected)
    memory: 15Ti # 64 Gi * 6 replicas * 20 concurrent jobs * 2 runners (public & protected)
