---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: retry-trigger-jobs
  namespace: custom
spec:
  schedule: "*/15 * * * *" # Every 15 minutes
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      activeDeadlineSeconds: 3600 # terminate any running job after 1 hour
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: retry-trigger-jobs
            image: ghcr.io/spack/retry-trigger-jobs:0.0.2
            imagePullPolicy: IfNotPresent
            resources:
              requests:
                cpu: 500m
                memory: 50M
            args:
              - "--hours"
              - "2"
              - "--projectid"
              - "57"
            env:
            - name: GITLAB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: delete-stale-branches-credentials
                  key: gitlab-token
            envFrom:
              - configMapRef:
                  name: python-scripts-sentry-config
          nodeSelector:
            spack.io/node-pool: base
