{
 "title": "GitLab CI Failures",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "CI Failures by Error Taxonomy",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "error_taxonomy.keyword",
       "id": "2",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Status of Completed Jobs",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  CAST(COUNT(status) as float) as success\n  from ci_builds\n  where $__timeFilter(\"finished_at\") and status = 'success';"
    },
    {
     "rawSql": "SELECT\n  CAST(COUNT(status) as float) as failed\n  from ci_builds\n  where $__timeFilter(\"finished_at\") and status = 'failed';"
    }
   ]
  },
  {
   "title": "CI Failures by GitLab Failure Reason",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 8 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "build_failure_reason.keyword",
       "id": "2",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Number of Completed Jobs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(1) FROM ci_builds\nWHERE $__timeFilter(\"finished_at\") AND (status = 'success' OR status = 'failed');"
    }
   ]
  },
  {
   "title": "Number of CI Failures by Time Unit",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  }
 ]
}