---
kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: spack-group-runner-secret
  namespace: gitlab
  creationTimestamp: null
spec:
  template:
    metadata:
      name: spack-group-runner-secret
      namespace: gitlab
      creationTimestamp: null
  encryptedData:
    runner-registration-token: AgBEKMCRpUGUVYM51rwKh/vWXtbK9mr4UDsZOKDq0Zr+gStNo5TCrrXXH2ETAFeIdko+WjJTVU/5otnSUwC6K7NOQNs5q7HdAs9xffCKKHnsRCmgVlIuSImuj1sFZ9t8tluDWwaqIOGwJo0gWmhI7D2oMlhgsxT4cQPk3uuXdw6YsMILIx/Duwg9qMcJdxLxkICO1PV9CUS7l2zDP/OP4UeEOJpSRwE1B6e0DSnYYl3b9VV65PUyAmTMZXd9/YZ3opeDduVRJJj64xcuiyM+MuUGZ3C99iKTo16AaUgsY0qY14d+EDHnwHhrHnHanbd3ozOVHA4HukOOaZ53qDqTqmRAL/MaCrtwO1JGdt+iliRMLhOgsnVCoAUJ58uao+QIKOaIUuPFTXNdtONUclKJWlb+i3MxHs/BC8PLD5WDi5EVflWX4n5Nq6rKm8Ax3hYZM5kaHxukTKdVJcpxJKY6jWt1VqVID+yYISoHk2Bt8OZHaj/2TB3a2gP2S5hbVhjT/usy6AVKwOWeK0fhRIIi2gMsgk2XkAqrDf0VNI9Svs5yEdqWQe52K9LU+6BNgqt4hG1OKZm49x1KB2gUyaYbDyf8a1MyQZo4FkRf9uCupV5mOeW35AixCL1iFrNBj3SyiahjcMwed3nKlsim72n/gTzDHm3yadB+VPGhO7oXP8geMHTclgOWiUr1pbGDI3z1Tduxw2deXsfK+3m6rw46nFT6pcV5WQgpfHj+3YhbBA==
    runner-token: AgA6rpZkGonZjS1P6OO5pCsOhv4YUeC2/cExZmIYK3rAqbjViu+BYIl8hpMNumR6GyVYFUgw0FuZqVE07F6vwaO0nEcZYSrD1ERrgWHFisDQ4XCN71QcSqhA0wzxYkqjFczVXTI4rVb9c07o2PCTfk9nkgCZN/dDiJktaZnJV0cf0F+/E/X1AKBmYCDszH4eRsa398cJR2FZbV7e30JWRU6UFymWtKLpAURt6gA80nLgvZ/vM4P+zJb0sN2LTXaBFn30CPlb0a7tYt4T6DjsvSjTNbsAZNdB4hI5vNYOL7yBQclRSQ1xvq5inAgtSWgmEhZ1UhwScVYUeOJQ9u66xObpV91HyBWtbm6cb/UZzvi5CM7ydKOeVgL0JsnZA0ly1UFY+YmjxW+fiAV6BGkPizPz5QMCgqWEBDElSAVxlMNkVo0WLZCJOyYnWZQpJHBBQT+MNCo7CiNQgrs2GNoKFdcuSZTtFHtygOokjeSaFVPjYRxyUQjxKiXdv0Ri5MBOuOitEhfBGlL6mOcJnh012riD4zXVTGV3zJ2n6B27zeyimc/hOTKNRWeRAKiwla8EIOGeKd+x2gLXqFOMAiXDr/JYfNwPSq4Da+SPS41IQAgA0Dsg80ME+0rSKEz37hDWouCw7gGBotrVk+ef5nUDBRo8Qh+prof1Yn9YymhR8rIDZikId7o2b3Y/wyRWluCRcaU=
