apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../production/fluent-bit/release.yaml
patches:
  - target:
      kind: HelmRelease
      name: fluent-bit
      namespace: fluent-bit
    patch: |-
      spec:
        values:
          serviceAccount:
            $patch: replace
            annotations:
              eks.amazonaws.com/role-arn: arn:aws:iam::588562868276:role/FluentBitRole-staging
