# Generated by Django 5.1.4 on 2025-01-03 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobdatadimension",
            name="infrastructure_error",
            field=models.GeneratedField(
                db_persist=True,
                expression=models.Q(
                    models.Q(
                        ("status", "failed"),
                        models.Q(
                            (
                                "error_taxonomy__in",
                                [
                                    "spack_error",
                                    "build_error",
                                    "concretization_error",
                                    "module_not_found",
                                ],
                            ),
                            _negated=True,
                        ),
                        models.Q(
                            ("error_taxonomy", "failed_to_get_specs"),
                            ("job_type", "rebuild-index"),
                            _negated=True,
                        ),
                    )
                ),
                help_text='Whether or not this job is an "infrastructure error", or a legitimate CI failure.',
                output_field=models.BooleanField(),
            ),
        ),
    ]
