# Generated by Django 4.2.4 on 2023-09-22 20:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_timerphase_rename_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="arch",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="build_jobs",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="compiler_name",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="compiler_version",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="job_size",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="package_variants",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="package_version",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="stack",
            field=models.CharField(max_length=128, null=True),
        ),
    ]
