# Generated by Django 5.1.4 on 2025-01-22 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_jobdatadimension_infrastructure_error"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobdatadimension",
            name="gitlab_failure_reason",
            field=models.CharField(
                help_text="The failure reason reported by GitLab", max_length=256, null=True
            ),
        ),
        migrations.AddField(
            model_name="jobdatadimension",
            name="job_exit_code",
            field=models.IntegerField(
                help_text="The exit code of the job reported by GitLab", null=True
            ),
        ),
    ]
