# Generated by Django 5.1.5 on 2025-01-21 22:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_migrate_dimensional_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobfact",
            name="id",
        ),
        migrations.AlterField(
            model_name="jobfact",
            name="job",
            field=models.PositiveBigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.RemoveConstraint(
            model_name="jobfact",
            name="job-fact-composite-key",
        ),
        # TODO: Uncomment once done testing
        # migrations.DeleteModel(
        #     name="JobDataDimension",
        # ),
    ]
