# Generated by Django 4.2.4 on 2024-01-25 00:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_jobpod_node_alter_job_aws_alter_job_duration_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterModelTable(
                    name="jobpod",
                    table="analytics_jobpod",
                ),
                migrations.AlterModelTable(
                    name="node",
                    table="analytics_node",
                ),
            ],
            database_operations=[],
        )
    ]
