# Generated by Django 5.1.5 on 2025-06-05 20:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_auto_20250121_2212"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobfact",
            name="gitlab_clear_worktree",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
