# Generated by Django 5.1.5 on 2025-07-15 20:44

import django.db.models.expressions
from django.db import migrations, models

iso_timestamp_sql = r"""
CREATE FUNCTION iso_timestamp(text)
    RETURNS TIMESTAMP WITHOUT TIME ZONE
    AS $$ SELECT CASE   WHEN $1 ~ '^\d\d\d\d-?\d\d-?\d\dT\d\d:?\d\d:?\d\d$'
                        THEN $1::timestamp
                        ELSE null end $$
    SET DateStyle = 'ISO,YMD'
    LANGUAGE SQL IMMUTABLE STRICT;
"""


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_jobfact_gitlab_clear_worktree"),
    ]

    operations = [
        migrations.RunSQL(
            sql=iso_timestamp_sql, reverse_sql="DROP FUNCTION iso_timestamp"
        ),
        migrations.AddField(
            model_name="jobfact",
            name="started_at",
            field=models.GeneratedField(
                db_comment="Represented in UTC",
                db_persist=True,
                expression=django.db.models.expressions.RawSQL(
                    output_field=models.DateTimeField(),
                    params=[],
                    sql="\niso_timestamp(  -- Custom function implemented in the migration\n    SUBSTR(start_date_id::text, 1, 4)\n    || '-' ||\n    SUBSTR(start_date_id::text, 5, 2)\n    || '-' ||\n    SUBSTR(start_date_id::text, 7, 2)\n    || 'T' ||  -- Separation between date and time\n    SUBSTR(start_time_id::text, 1, 2)\n    || ':' ||\n    SUBSTR(start_time_id::text, 3, 2)\n    || ':' ||\n    SUBSTR(start_time_id::text, 5, 2)\n)\n",
                ),
                output_field=models.DateTimeField(),
            ),
        ),
        migrations.AddField(
            model_name="jobfact",
            name="finished_at",
            field=models.GeneratedField(
                db_comment="Represented in UTC",
                db_persist=True,
                expression=django.db.models.expressions.RawSQL(
                    output_field=models.DateTimeField(),
                    params=[],
                    sql="\niso_timestamp(  -- Custom function implemented in the migration\n    SUBSTR(start_date_id::text, 1, 4)\n    || '-' ||\n    SUBSTR(start_date_id::text, 5, 2)\n    || '-' ||\n    SUBSTR(start_date_id::text, 7, 2)\n    || 'T' ||  -- Separation between date and time\n    SUBSTR(start_time_id::text, 1, 2)\n    || ':' ||\n    SUBSTR(start_time_id::text, 3, 2)\n    || ':' ||\n    SUBSTR(start_time_id::text, 5, 2)\n)\n + duration",
                ),
                output_field=models.DateTimeField(),
            ),
        ),
    ]
