# Generated by Django 4.2.4 on 2024-01-25 00:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_alter_jobpod_table_alter_node_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="errortaxonomy",
            table=None,
        ),
        migrations.AlterModelTable(
            name="job",
            table=None,
        ),
        migrations.AlterModelTable(
            name="jobpod",
            table=None,
        ),
        migrations.AlterModelTable(
            name="node",
            table=None,
        ),
        migrations.AlterModelTable(
            name="timer",
            table=None,
        ),
        migrations.AlterModelTable(
            name="timerphase",
            table=None,
        ),
    ]
