# Generated by Django 5.1.5 on 2025-07-16 18:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_jobfact_started_at_finished_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobfact",
            name="finished_at",
        ),
        migrations.RemoveField(
            model_name="jobfact",
            name="started_at",
        ),
        migrations.RemoveConstraint(
            model_name="datedimension",
            name="date-key-value",
        ),
        migrations.AlterField(
            model_name="datedimension",
            name="date_key",
            field=models.CharField(
                db_comment="The date this row represents formatted as <YYYY><MM><DD>",
                max_length=8,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.RemoveConstraint(
            model_name="timedimension",
            name="time-key-value",
        ),
        migrations.AlterField(
            model_name="timedimension",
            name="time_key",
            field=models.CharField(
                db_comment="The time this row represents formatted as <HOUR><MINUTE><SECOND>",
                max_length=6,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
