# Generated by Django 4.2.4 on 2024-01-25 21:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_jobpod_node_alter_job_aws_alter_job_duration_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="unnecessary",
            field=models.BooleanField(
                default=False, help_text="Whether this job has 'No need to rebuild' in its trace."
            ),
        ),
    ]
