# Generated by Django 4.2.4 on 2024-02-09 17:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_job_unnecessary"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobAttempt",
            fields=[
                ("job_id", models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ("project_id", models.PositiveBigIntegerField()),
                ("commit_id", models.PositiveBigIntegerField()),
                ("name", models.CharField(max_length=128)),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField()),
                ("ref", models.CharField(max_length=256)),
                ("is_retry", models.BooleanField()),
                ("is_manual_retry", models.BooleanField()),
                ("attempt_number", models.PositiveSmallIntegerField()),
                ("final_attempt", models.BooleanField()),
                ("status", models.CharField(max_length=32)),
                ("error_taxonomy", models.CharField(max_length=64)),
            ],
        ),
    ]
