# Generated by Django 5.1.5 on 2025-07-16 21:33

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_fix_time_dimension_time_key"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="timedimension",
            constraint=models.CheckConstraint(
                condition=models.Q(("time_key__range", (0, 235959))),
                name="time-key-value",
            ),
        ),
        migrations.AddField(
            model_name="jobfact",
            name="started_at",
            field=models.GeneratedField(
                db_comment="Represented in UTC",
                db_persist=True,
                expression=django.db.models.expressions.RawSQL(
                    output_field=models.DateTimeField(),
                    params=[],
                    sql="\niso_timestamp(  -- Custom function implemented in the migration\n    SUBSTR(start_date_id, 1, 4)\n    || '-' ||\n    SUBSTR(start_date_id, 5, 2)\n    || '-' ||\n    SUBSTR(start_date_id, 7, 2)\n    || 'T' ||  -- Separation between date and time\n    SUBSTR(start_time_id, 1, 2)\n    || ':' ||\n    SUBSTR(start_time_id, 3, 2)\n    || ':' ||\n    SUBSTR(start_time_id, 5, 2)\n)\n",
                ),
                output_field=models.DateTimeField(),
            ),
        ),
        migrations.AddField(
            model_name="jobfact",
            name="finished_at",
            field=models.GeneratedField(
                db_comment="Represented in UTC",
                db_persist=True,
                expression=django.db.models.expressions.RawSQL(
                    output_field=models.DateTimeField(),
                    params=[],
                    sql="\niso_timestamp(  -- Custom function implemented in the migration\n    SUBSTR(start_date_id, 1, 4)\n    || '-' ||\n    SUBSTR(start_date_id, 5, 2)\n    || '-' ||\n    SUBSTR(start_date_id, 7, 2)\n    || 'T' ||  -- Separation between date and time\n    SUBSTR(start_time_id, 1, 2)\n    || ':' ||\n    SUBSTR(start_time_id, 3, 2)\n    || ':' ||\n    SUBSTR(start_time_id, 5, 2)\n)\n + duration",
                ),
                output_field=models.DateTimeField(),
            ),
        ),
    ]
