# Generated by Django 4.2.4 on 2024-02-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_jobattempt"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobattempt",
            name="section_timers",
            field=models.JSONField(
                default=dict, help_text="The GitLab CI section timers for this job.", null=True
            ),
        ),
    ]
