# Generated by Django 5.1.5 on 2025-07-22 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_restore_constraints_generated_fields'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='jobfact',
            index=models.Index(fields=['started_at'], name='core_jobfact_started_at'),
        ),
        migrations.AddIndex(
            model_name='jobfact',
            index=models.Index(fields=['finished_at'], name='core_jobfact_finished_at'),
        ),
    ]
