# Generated by Django 5.2.6 on 2025-10-02 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_jobfact_core_jobfact_started_at_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='gitlabjobdatadimension',
            name='unique-gitlab-job-data',
        ),
        migrations.RenameField(
            model_name='gitlabjobdatadimension',
            old_name='commit_id',
            new_name='pipeline_id',
        ),
        migrations.AddConstraint(
            model_name='gitlabjobdatadimension',
            constraint=models.UniqueConstraint(fields=('gitlab_runner_version', 'ref', 'tags', 'pipeline_id'), name='unique-gitlab-job-data'),
        ),
    ]
