# Generated by Django 4.2.4 on 2024-03-20 17:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_alter_jobattempt_error_taxonomy_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["started_at"], name="core_job_started_b88deb_idx"
            ),
        ),
    ]
