# Generated by Django 5.2.7 on 2025-10-07 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_gitlabjob_commit_id_to_pipeline_id'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='gitlabjobdatadimension',
            name='unique-gitlab-job-data',
        ),
        migrations.AddField(
            model_name='gitlabjobdatadimension',
            name='parent_pipeline_id',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AddConstraint(
            model_name='gitlabjobdatadimension',
            constraint=models.UniqueConstraint(fields=('gitlab_runner_version', 'ref', 'tags', 'pipeline_id', 'parent_pipeline_id'), name='unique-gitlab-job-data'),
        ),
    ]
