# Generated by Django 4.2.4 on 2024-05-17 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_dimensional_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="PackageHashDimension",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hash", models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="TimerDataDimension",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cache", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="TimerFact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_time", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="TimerPhaseDimension",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=64, unique=True)),
                ("is_subphase", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="TimerPhaseFact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.FloatField()),
                (
                    "ratio_of_total",
                    models.FloatField(
                        help_text="The fraction of the timer total that this phase contributes to."
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.jobdatadimension",
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.packagedimension",
                    ),
                ),
                (
                    "package_hash",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.packagehashdimension",
                    ),
                ),
                (
                    "phase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.timerphasedimension",
                    ),
                ),
                (
                    "timer_data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.timerdatadimension",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="timerphasedimension",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("is_subphase", True), ("path__contains", "/")),
                    models.Q(
                        ("is_subphase", False),
                        models.Q(("path__contains", "/"), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="consistent-subphase-path",
            ),
        ),
        migrations.AddField(
            model_name="timerfact",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.jobdatadimension"
            ),
        ),
        migrations.AddField(
            model_name="timerfact",
            name="package",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.packagedimension"
            ),
        ),
        migrations.AddField(
            model_name="timerfact",
            name="package_hash",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="core.packagehashdimension",
            ),
        ),
        migrations.AddField(
            model_name="timerfact",
            name="timer_data",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="core.timerdatadimension",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="timerdatadimension",
            unique_together={("cache",)},
        ),
        migrations.AlterUniqueTogether(
            name="timerphasefact",
            unique_together={("job", "timer_data", "phase", "package", "package_hash")},
        ),
        migrations.AlterUniqueTogether(
            name="timerfact",
            unique_together={("job", "timer_data", "package", "package_hash")},
        ),
    ]
