# Generated by Django 5.1.5 on 2025-10-24 16:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_remove_gitlabjobdatadimension_unique_gitlab_job_data_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="packagespecdimension",
            name="no-missing-fields",
        ),
        migrations.AddConstraint(
            model_name="packagespecdimension",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("hash__length", 32),
                        ("name__length__gt", 0),
                        ("version__length__gt", 0),
                    ),
                    models.Q(
                        ("arch", ""),
                        ("compiler_name", ""),
                        ("compiler_version", ""),
                        ("hash", ""),
                        ("name", ""),
                        ("variants", ""),
                        ("version", ""),
                    ),
                    _connector="OR",
                ),
                name="no-missing-fields",
            ),
        ),
    ]
