# Generated by Django 5.1.5 on 2025-12-19 23:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_remove_packagespecdimension_no_missing_fields_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobresultdimension",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("build", "Build"),
                    ("dotenv", "Dotenv"),
                    ("generate", "Generate"),
                    ("no-specs-to-rebuild", "No Specs to Rebuild"),
                    ("rebuild-index", "Rebuild Index"),
                    ("copy", "Copy"),
                    ("unsupported-copy", "Unsupported Copy"),
                    ("sign-pkgs", "Sign Packages"),
                    ("protected-publish", "Protected Publish"),
                ],
                max_length=19,
            ),
        ),
        migrations.AlterField(
            model_name="spackjobdatadimension",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("build", "Build"),
                    ("dotenv", "Dotenv"),
                    ("generate", "Generate"),
                    ("no-specs-to-rebuild", "No Specs to Rebuild"),
                    ("rebuild-index", "Rebuild Index"),
                    ("copy", "Copy"),
                    ("unsupported-copy", "Unsupported Copy"),
                    ("sign-pkgs", "Sign Packages"),
                    ("protected-publish", "Protected Publish"),
                ],
                max_length=19,
            ),
        ),
    ]
