# Generated by Django 5.1.4 on 2026-03-26 19:26

import math
from itertools import batched

from django.db import connections, migrations, models
from tqdm import tqdm

# def migrate_protected_and_service_fields(apps, _):
#     JobFact = apps.get_model("core", "JobFact")
#     GitlabJobDataDimension = apps.get_model("core", "GitlabJobDataDimension")

#     BATCH_SIZE = 5_000
#     for job_ids in batched(
#         JobFact.objects.values_list("job_id", flat=True).iterator(
#             chunk_size=BATCH_SIZE
#         ),
#         BATCH_SIZE,
#     ):
#         with connections["gitlab"].cursor() as cursor:
#             QUERY = """
#             SELECT
#                 p_ci_builds.id,
#                 protected,
#                 EXISTS(
#                     SELECT *
#                     FROM p_ci_build_tags
#                     LEFT JOIN tags ON p_ci_build_tags.tag_id = tags.id
#                     WHERE p_ci_build_tags.build_id IN %(job_ids)s AND tags.name = 'service'
#                 ) AS service
#             FROM p_ci_builds
#             WHERE
#                 p_ci_builds.id IN %(job_ids)s
#             """
#             cursor.execute(QUERY, {"job_ids": job_ids})
#             results = typing.cast(list[tuple[int, bool, bool]], cursor.fetchall())
#             lookup_table = {
#                 job_id: {"protected": protected, "service": service}
#                 for job_id, protected, service in results
#             }

#             job_facts = JobFact.objects.select_related("gitlab_job_data").filter(
#                 job_id__in=job_ids
#             )
#             for job_fact in job_facts:
#                 old = job_fact.gitlab_job_data
#                 new_gitlab_job_data, _ = GitlabJobDataDimension.objects.get_or_create(
#                     gitlab_runner_version=old.gitlab_runner_version,
#                     ref=old.ref,
#                     tags=old.tags,
#                     pipeline_id=old.pipeline_id,
#                     parent_pipeline_id=old.parent_pipeline_id,
#                     protected=lookup_table[job_fact.job_id]["protected"],
#                     service=lookup_table[job_fact.job_id]["service"],
#                 )
#                 job_fact.gitlab_job_data = new_gitlab_job_data
#                 job_fact.save()


def migrate_protected_and_service_fields(apps, _):
    JobFact = apps.get_model("core", "JobFact")
    GitlabJobDataDimension = apps.get_model("core", "GitlabJobDataDimension")

    BATCH_SIZE = 5_000

    for batch in tqdm(
        batched(
            JobFact.objects.values_list("job_id", "gitlab_job_data_id").iterator(
                chunk_size=BATCH_SIZE
            ),
            BATCH_SIZE,
        ),
        total=math.ceil((JobFact.objects.count() / BATCH_SIZE)),
    ):
        job_ids = tuple(job_id for job_id, _ in batch)

        with connections["gitlab"].cursor() as cursor:
            QUERY = """
            SELECT
                p_ci_builds.id,
                protected,
                EXISTS(
                    SELECT 1
                    FROM p_ci_build_tags
                    JOIN tags ON p_ci_build_tags.tag_id = tags.id
                    WHERE p_ci_build_tags.build_id = p_ci_builds.id AND tags.name = 'service'
                ) AS service
            FROM p_ci_builds
            WHERE p_ci_builds.id IN %(job_ids)s
            """
            cursor.execute(QUERY, {"job_ids": tuple(job_ids)})
            gitlab_lookup = {
                job_id: (protected, service)
                for job_id, protected, service in cursor.fetchall()
            }

        # Group job IDs by (gitlab_job_data_id, protected, service).
        # The reason we group by this combination of values is because these combinations represent all possible
        # new rows for the GitlabJobDataDimension table. Since each entry in that table has now two new independent
        # values, the maximum amount of new rows is 4x the existing count. We want to create as few new rows as
        # possible, so jobs are grouped by combination of values (existing values via gitlab_job_data_by_id, + these two new values).
        # Once these groupings are made, the new row in GitlabJobDataDimension is created, and all jobs that share that
        # unique combination of values are pointed to that new row.
        groups: dict[tuple[int, bool, bool], list[int]] = {}  # type: ignore
        for job_id, gitlab_job_data_id in batch:
            if job_id not in gitlab_lookup:
                print(f"Job ID {job_id} not found in lookup")
                continue

            key = (gitlab_job_data_id, *gitlab_lookup[job_id])
            groups.setdefault(key, []).append(job_id)

        # Fetch all old dimensions in one query
        gitlab_job_data_by_id = {
            row.id: row
            for row in GitlabJobDataDimension.objects.filter(
                id__in={row_id for row_id, *_ in groups}
            )
        }

        for (row_id, protected, service), group_job_ids in groups.items():
            old = gitlab_job_data_by_id[row_id]
            new_dim, _ = GitlabJobDataDimension.objects.get_or_create(
                gitlab_runner_version=old.gitlab_runner_version,
                ref=old.ref,
                tags=old.tags,
                pipeline_id=old.pipeline_id,
                parent_pipeline_id=old.parent_pipeline_id,
                protected=protected,
                service=service,
            )
            JobFact.objects.filter(job_id__in=group_job_ids).update(
                gitlab_job_data=new_dim
            )


def remove_old_protected_and_service(apps, _):
    GitlabJobDataDimension = apps.get_model("core", "GitlabJobDataDimension")
    GitlabJobDataDimension.objects.filter(protected=None, service=None).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_add_dotenv_job_type"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="gitlabjobdatadimension",
            name="unique-gitlab-job-data",
        ),
        migrations.AddField(
            model_name="gitlabjobdatadimension",
            name="protected",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="gitlabjobdatadimension",
            name="service",
            field=models.BooleanField(null=True),
        ),
        migrations.AddConstraint(
            model_name="gitlabjobdatadimension",
            constraint=models.UniqueConstraint(
                fields=(
                    "gitlab_runner_version",
                    "ref",
                    "tags",
                    "pipeline_id",
                    "parent_pipeline_id",
                    "protected",
                    "service",
                ),
                name="unique-gitlab-job-data",
            ),
        ),
        migrations.RunPython(
            migrate_protected_and_service_fields, migrations.RunPython.noop
        ),
        migrations.RunPython(
            remove_old_protected_and_service, migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name="gitlabjobdatadimension",
            name="protected",
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name="gitlabjobdatadimension",
            name="service",
            field=models.BooleanField(),
        ),
    ]
