# Generated by Django 4.2.4 on 2024-05-21 17:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_migrate_timer_data"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ErrorTaxonomy",
            new_name="LegacyErrorTaxonomy",
        ),
        migrations.RenameModel(
            old_name="Job",
            new_name="LegacyJob",
        ),
        migrations.RenameModel(
            old_name="JobAttempt",
            new_name="LegacyJobAttempt",
        ),
        migrations.RenameModel(
            old_name="JobPod",
            new_name="LegacyJobPod",
        ),
        migrations.RenameModel(
            old_name="Node",
            new_name="LegacyNode",
        ),
        migrations.RenameModel(
            old_name="Timer",
            new_name="LegacyTimer",
        ),
        migrations.RenameModel(
            old_name="TimerPhase",
            new_name="LegacyTimerPhase",
        ),
        migrations.operations.models.RenameIndex(
            model_name="legacyjob",
            new_name="core_legacy_started_8e0fbb_idx",
            old_name="core_job_started_b88deb_idx",
        ),
    ]
