# Generated by Django 4.2.4 on 2024-06-24 21:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_rename_legacy_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="runnerdimension",
            name="name",
            field=models.CharField(max_length=64),
        ),
    ]
