# Generated by Django 4.2.13 on 2024-07-18 16:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_alter_runnerdimension_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobdatadimension",
            name="gitlab_section_timers",
            field=models.JSONField(
                db_comment="The GitLab CI section timers for this job.", default=dict
            ),
        ),
    ]
