# Generated by Django 4.2.13 on 2024-08-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_alter_runnerdimension_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobdatadimension",
            name="is_build",
        ),
        migrations.AddField(
            model_name="jobdatadimension",
            name="gitlab_section_timers",
            field=models.JSONField(
                db_comment="The GitLab CI section timers for this job.", default=dict
            ),
        ),
        migrations.AddField(
            model_name="jobdatadimension",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("build", "Build"),
                    ("generate", "Generate"),
                    ("no-specs-to-rebuild", "No Specs to Rebuild"),
                    ("rebuild-index", "Rebuild Index"),
                    ("copy", "Copy"),
                    ("unsupported-copy", "Unsupported Copy"),
                    ("sign-pkgs", "Sign Packages"),
                    ("protected-publish", "Protected Publish"),
                ],
                default="build",
                max_length=19,
            ),
            preserve_default=False,
        ),
    ]
