# Generated by Django 4.2.13 on 2024-10-10 19:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0020_remove_jobdatadimension_is_build_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LegacyErrorTaxonomy",
        ),
        migrations.RemoveField(
            model_name="legacyjob",
            name="node",
        ),
        migrations.RemoveField(
            model_name="legacyjob",
            name="pod",
        ),
        migrations.DeleteModel(
            name="LegacyJobAttempt",
        ),
        migrations.RemoveField(
            model_name="legacytimer",
            name="job",
        ),
        migrations.RemoveField(
            model_name="legacytimerphase",
            name="timer",
        ),
        migrations.DeleteModel(
            name="LegacyJob",
        ),
        migrations.DeleteModel(
            name="LegacyJobPod",
        ),
        migrations.DeleteModel(
            name="LegacyNode",
        ),
        migrations.DeleteModel(
            name="LegacyTimer",
        ),
        migrations.DeleteModel(
            name="LegacyTimerPhase",
        ),
    ]
