# Generated by Django 4.2.13 on 2024-10-31 20:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0021_delete_legacyerrortaxonomy_remove_legacyjob_node_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="packagespecdimension",
            name="no-missing-fields",
        ),
        migrations.AddConstraint(
            model_name="packagespecdimension",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("arch__length__gt", 0),
                        ("hash__length", 32),
                        ("name__length__gt", 0),
                        ("version__length__gt", 0),
                    ),
                    models.Q(
                        ("arch", ""),
                        ("compiler_name", ""),
                        ("compiler_version", ""),
                        ("hash", ""),
                        ("name", ""),
                        ("variants", ""),
                        ("version", ""),
                    ),
                    _connector="OR",
                ),
                name="no-missing-fields",
            ),
        ),
    ]
