# Secret used for creating the gitlab_ro_user with the gitlab_ro_user_job.yaml
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitlab-ro-postgresql-password
  namespace: gitlab
spec:
  encryptedData:
    postgresql-gitlab-ro-user-password: AgApYZc9PnPY/WsglM0Q7q61iOnii5HuAJpiTPvSunfQS9q96RnyJCv4Il6Xf71r3WKoKCN3FObXp1ZFNMdBjr8Gy0T4mBXm3ZMVDHiGR7T2Nf3Spaj0BpRiOu8IZG0EYE/VHFuVmdil0URJybRpJQrZIpTL5rVmfgbOyRsdC1B2oLaLEi/V2xSvXi248r7/UZBX4f0FpBXiTLABb7eETH/KsJhGHaP6dUvOvf/4OlSwIOd/TbGPrJiLzDUx1vbSfeQE39IET1zg3WMEnSVbnyG43cI1jr0MiLqcxfW4z7lwRdw6ib9lTzUCp2T/SNK3eQT8B1Eg7Ltqi6/mYi5nbKZYLYF26t7mbrMLKZ4EiufwQ4BDT/S54Ffampu13082wikgZtMGc3bAUhLaxoWb7hDdv1rhx8mvYL6xzOOG1vyGIxGBHehq+HeOklZqbHevsnb98rZblQRAD8VgW+wzpfp/MWL08cXhGpxvLtRr/ypYBGarTau+nksUuaS4OjCOnzE87yVb5t6BnFeyhOsz5QzPrwF6g5hKZp7iq4X+aCPbnSpuYjUbabvRbJpU/w1Ud7qsdHKL8dRB2ksJEUdvmWZtLmyxlLqAMLTRIJjM5RCRF+CY+xOpUtHLkQ4SjHm2eo9mM5FRPzEgC70VyQf0bIEt7B4lEOAHFXe3mX+W8vSwsKVurmvbyvhtMqZvAGaqVmPm4eA8cp1jPVgQGIG+gm85nrEvvM0DSkYBBL8TpdNu4A==
  template:
    metadata:
      annotations:
        kustomize.toolkit.fluxcd.io/reconcile: disabled
        sealedsecrets.bitnami.com/managed: "true"
---
# Secret used for setting up the metabase postgres instance's postgres user
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: metabase-postgresql-password
  namespace: monitoring
spec:
  encryptedData:
    postgresql-password: AgAgMeFVclW+75hZ8hVOqxlpPN0MRAkSl+3PkW732r7FPQ+glspr2vMxdaDRBUOMm4Z6lm4QSYSmZSvENczkVIG5wg2Up7sb2DYis6j0sQiYwJKY21k5VgaZlFzrXfWsthHw5ISutvhhebypx08OcVP6a30mxdJgBZPb/IrOGycnJYlbKnQQnts4VpKEcxLOXOlPUj8iECQMO7/Bk1/B570FTlNhMaeJVsLofRc+FmLbI+uWvvRjnHZG4NLy3pQOWm+q435Xz7U6owoviTvD/EOz6mkE2wVLe82oN+DgPAFtWiwNE3H61A42tIAA17gsjFFiEtye6fjt32NXtgxxQSOfnbkmkPjKBadjL0x5Hgavov7IJGM7VI9ItO483X9qE85knt9irsk4dxTTB07i81gFNW2/aMHQslnhWuCR0Q0m42K1c514I4JQVQ2hV0p53XqQzuSF311Sg8aEE1z31/UE9yv4wwz29YRwW5Oyrkuen6rhqXaClMoYe2t0rdqT93TBGbPXxGFwkyeCvfARiEPs9VS5v6AJJXIAvl8FO1unff1h7/sGnvF2TLke+by6XVCpTXoXKq0bAf9vj39O8T256MmUWjUuMrmwM8Ux/cK3D5rvNYrn9LZu+k9spbf9JErDUvP66AB+BpFzhYQaQ5ScGpI5C3o0JAcJ8Aktfj9P+5m9lk8TKkkxZzDurAoY9JNcipr0sbh/ZcI+zVJE2H0Y10XqaRwosY/anEZcp91DOrzGKZCfhl7V
  template:
    metadata:
      annotations:
        kustomize.toolkit.fluxcd.io/reconcile: disabled
        sealedsecrets.bitnami.com/managed: "true"
---
# Secret used to log into the GitLab postgres instance
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitlab-postgresql-secrets
  namespace: monitoring
spec:
  encryptedData:
    gitlab-postgresql-host: AgBbAgCW2lsh2whidQ3qr9EM95eZt+I6vi6aSubcjjp6HP8O3P4PdaU7/0LrQyH70DOLNOZhje4qsMadsWSFOjQ1peaHw8SN9kDTW2pgUSIuYUSjJkh2nNmNgMyR/tVd/avuUAv1kEpNjg2U5SBgzaM4M9W+FtxlR1cCwgEkJ8xR0E3kW4DrDzv1H5CXXPdboKFf0Bth5b5NMAahS62CdRuutnEfndCnUWod2SxryaHbT4xiw60h34UO5BFjybzgpcdP97Y0Pp+gJeE0j2aLj8ODXSqs/STDHmpOktXt7YcaGAlcuOFOeTGW1PXREAp1NWRQfQBjcbG3JCTLHQ1VkKB/naR3R2jUMEZ55/97E9JUEEjG9vqYOQx88szpHRrbKWL0FsHQin4CrYQinLoud5pZFL23GUwgQv2FzMdr9sbhpDqTR/M3qS3UoyHAnZAeuXBxtS9HZ8ZwIf2ZmZE77bakKgtEvmcY02Fdr77Do8W5RdC1XpqCz2Mo2z79UzKT/wjR/WW7Ben1XS0J5wm+e+A1TUVKIbo/tcZWwkfzr8Si61sOI7TYfymJChtJwkiL8uYcz6yH9dNkCKLlCpk4/G728jx3/JFYMXk4e64RqfCkb0JrCkMuGY6ANUG6XyXTmcrNZrNpJ3uNg7GJ0ARB8MDwwIQLt6pTMarxH7+8W4olypLr2k43lplla+dXgaS51S6jSKtN7uUcEZ1Wr4fv89lSE48BckHO+/hp22UqVX848TOrRs3mkSkJZV5FCaZHLw1KKT1nssI0txL4
    gitlab-postgresql-password: AgBA29+cFpc4g5uULTaSAEXUKsQLHJU5R2JVNTEj0laWSx5hloNhjB+URQXZpikF51HuhzHxH7xf+d+yC8S8MGkluWHdHbA96ND4h1riz4cc3NyWWz3RSBA6WaOtSqxValCQQ/TlSxXHj5QM+Lg+6KF5d2sG5Kv1byET+6ynBbaPElW8ujrsEqitjckWWFp79JOLhQ7uNVhQ+NCEF8XibSj7szRdSNbyhmqIswGPoanTs1MaymZEZfGXSUvndv+zaYJrHqWz6bQZotemuvKCdEq6Znwg3MLHlQbYMot4Vi6TBspTKHw/t1k97DwqsmJb0txaACpfo4btezKp173JzvGbYt4wfB2jyxNGhHfZ+SLBeqT3PMYBAasjeUiw0EEWtPjjATXNdlo1reAMNeQkUlCzxgUesCOHqktOdAduR6kJrW9Nqx+bo65VLc5KhUltaSZABYrNPG/GOjWGcb2w8WUnqvU5h5cbSPaZzPck3qppAMM/p/TixaoXSNnQUR6h89w4HICqfoWxPlnZLS38fogTb4lBycz2zGENGctqQBP5YFCWtw/V+QMmbee7ujlyHKSp5QYfSP1vyVNcGwvvfnrsaisfFS9om6i7b0nrPA/6viZ8s8F5cbCk8PxMAd1AUfprTdInlhFtLZC/KZFA1zsRMBd4m4wXXGpFWqXMkAi+1akjHdU5r0xuOPK7JXZ9Pebfqo0qw+ad457ykp+JePThUatxUA==
  template:
    metadata:
      annotations:
        kustomize.toolkit.fluxcd.io/reconcile: disabled
        sealedsecrets.bitnami.com/managed: "true"
