# Secret used for creating the gitlab_ro_user with the gitlab_ro_user_job.yaml
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitlab-ro-postgresql-password
  namespace: gitlab
spec:
  encryptedData:
    postgresql-gitlab-ro-user-password:
      AgAla4EIeFbix9G1bx5KgNpgagC/ZiAbWD8g4ak+m7aW6RplW9dUG9ceTLjFRpa5wUij3WaH0weETu/IY79M/cqJNJ8jhdjFq2lPvyimSjQc0RN8qEtMwKEppMvXE3BHCC4ys4dLDecYRWKfFOoBP/ewCin1RYqvsZVFUi8OveRbdXaE9fu3TQ5xxIOAHs0/glZ8icXWmTR691bd4iH5YSPhokBe6O89GEVvoUBQvrpSy4lhqAQS6u3sJVu8KGn4snBhXBNKyeG5nl1+haiI4mIcsr6lv5lzniHJ7cR2tMoniGtuhdE7NgvGAzuTLL4ms1Jyb9YBZJwtgtQcvOcs6ofUKuWkbM6XMZp22gLqtT+WKK/hVqGyX8Hwb/BckBERnNBvolZ5AhsdCockVJVSJlqMukZqJgZpPNhQgB+50eVaNhcUUbhCRO8wi0Ge4mrNgpCZrhU4bwk9PDahkl7hJT0fwJfTTJ+JI21O3AvBW6w9RKIcbBJvjW3AaMqzECSjsParo505lhoY7RHLTaS9LPZSdZdD8cYySgw4XFITFyuTSlIn05vqPieyIfziAGdm9nZ+9glW82oobvPUtv2bln8kdvoR0VMCGniMYvi1dA4UUwafLvm/nzzyBCuJOGFg+wIX6TvGFxM8DmZCE+g4gKr0xFpO2Yk96v2pm0bQZo8YfA7g9/6o3cBsItJtrD1EnT29+59bbDSNF73GHDBxim6QDFoJOLihxetcGC0+AAFr8g==
  template:
    metadata:
      annotations:
        kustomize.toolkit.fluxcd.io/reconcile: disabled
        sealedsecrets.bitnami.com/managed: "true"
---
# Secret used for setting up the metabase postgres instance's postgres user
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: metabase-postgresql-password
  namespace: monitoring
spec:
  encryptedData:
    postgresql-password:
      AgBUxBOADzwYaDx79Ijc04EdvUazH/sOnLJt3vuoKsd4Z23B5ZjmP+ZYhm6PgWiwUpspJwx5iVkCUiEzGrfky1c3jJK7EAAIdHLnVmQS+J4erzx+bJoCL/dUo0+q6jFq/9G2dc38OKikrVC0WRruoMDazHAHZzpu6+Sv9exvG7nBm+mIg9Zy0SUc7anut0q9Wr3YjquGAVqn0AQsG+RXmAtQY4eUqmAiSDidl204+8O/tr6cOkj57MNiQvNGtdzZBl8HM40hwcX3xf4Udr3FjtevHFS6bFnT0m4K6SCHFykTRS6XxpB8gm76aaM/6qcSfobut5R9KLQw0+VacXB1URhP5ySPaJOMn0FcL0i4JWX3bhB1h9JAdFkNjPa2EWKRVghVCw+pyDTTlOHluAlE1Po4b303Wph8riR2NWEiWOCxUVPKLxZn79taqs3BET5fFMf1DEzSTkfhXWqvLqU/cKPyg+yQpdqY72rllQCUmLWziL2xXzX3WQLcObKk2Yg+NOkuCcPAxBszTPFDrlWU3GHGMsxmGpf4E3Ay07W6QUozKuaYLC/9A8W3805IOO3szZ0XRCjAjlnQEsy+uEDpYBW+/IynlunWGgjxFAONwNJxhwpmNeLbbEy0Nbwvcy3xFCQX8GtUiju0z6Re9zyl8BZ8b5aziRQLuIY1FUlAWa/SNpGKbYHuXo5vn/CjPZ6XjGZDKnimjBWFSfz+AAmq5IIldfHUUobNBOd2Q6RcT2cH6IKLLWfK1Pw7
  template:
    metadata:
      annotations:
        kustomize.toolkit.fluxcd.io/reconcile: disabled
        sealedsecrets.bitnami.com/managed: "true"
---
# Secret used to log into the GitLab postgres instance
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitlab-postgresql-secrets
  namespace: monitoring
spec:
  encryptedData:
    gitlab-postgresql-host:
      AgBR1BtoZ+VZcRaFWRRyicixJCOEfls5ijerQ0D9kJrTPbw1dZkUkup1u0bgZnN6aK4xXpRajEBbT6o/n7Ub7czzzs9fEzz4DS6GBMZeGf86ObbsOstKBaHkN0JvYh2g917AYbc4zEORFDYnHdQFyiw8R749VGsxSdoGvT8Pkp4n+dpMdvC7nDvHENKURg1k8qNAUSW0NgGQfHH8RjhA3J1gRYBTGZlc7FUHudlDBBGoDNcrFmAy8SCVUWl63eZBUdIhqm7LF0A5T/HZTqoAoqeYJLH+k28ZChDKVZQ9LECx0Mb468xZX8jaeRqbrQ7J8r1gvMYNFeV7yZd4E2975FDjfDnMoRktwuJrXGrc+TFl+UvNB1PBkEDiBc6VUXhNSJnLDFO/xUf4WBMixrmHwXJ3iehCX9goj4FMdC5pgFv/AibuVe6AStNOQyvN3CuW6dBK5N70nluBBcmfy3FQpoH52Mq7TFWd2ml8tpKaRZVcLvDEbQ1yw/Z+a1PxmvIgZulc1D6Q3515jLlI4/WCXv2Yj/p6PivIvn4KfpYKFDNqvC0KpKad0mq8C6fhPACVtpMu7KA8b21CQBQnzoNNbH40VeFd+aipNwHhxspkA4h2hIiPrbCxR7PYFPyUBvKgjuGM7yVNYNkJlYNuanlh1I0hxbkOEWGedWIG5lZjnhBcy234sVUnoDN7JUzcm8la3Csue3EDGr5Y3F447M60WeMzTcW9z+b782YmgFznwjbFQA33QANr3XTCcdtubN0P0gWSNl5gLp5cfmjq
    gitlab-postgresql-password:
      AgABGC5Qp+4EvFtCVMbIqINh6ltOyeauFnOMTACliGBTrXnS+LF6Sm/nT9zozd765zzEW0DQCERyfBKepvn5Ch7qHFdueacpfh8+voPee1Xqv0I1Vn+9N3wBQplhUQCna76/SUMVQGXcoFzILPZFgvvqwKxBkMFCKuIT3yUlhkIDkXjbkVTAxWsViA/15SsKLz3vHZ1niHGpV3J441wvdfCh90LQV8zyEl2IHq7Intq5LgVgZcAQTSQ7KxgdXbr+78dvMivSnr1zkrRyczBQevqeIClKqHg5vbESU31eyt3gL3DnJXi7nRtBgszvJf/1CNKSO69jpf9XOsm0LB2vKLHRnFXCMQQwDWZ9Sv1pxT69VXpiV7LvCKpsoG/zmjC3TctWE30TPwkBDOBF4l7ejXnkiQrSuf0Ix/C4Rav5uIvhrd6sZN/kTQvs1WqkT8w27fvIbbDD5KbNJj/7rfPgA7WIBAV8nZO/JzfCVbv+vn24+cM/PHFi/VYYBlBoD7DW38gxZ3wI0cccNKD6/Ce2veAudoR1kpe/Qse89PPndpTa8R8+bCgJXXkxBpcdwJofNavidinfLTyD/nsgHPsZyw7LuxzIW9cfAks52XWUCD2PLb3TDUdBGlTPlbT9uUUhR6NNW1M/o5G6eHZxaa8okGoEDHM8Ob6JPUANu/8BoeXlDG8JLiAzdwxyLy7QZwp/0H9pS7RSTi3MQu/a7c3ydj/sERYVRA==
  template:
    metadata:
      annotations:
        kustomize.toolkit.fluxcd.io/reconcile: disabled
        sealedsecrets.bitnami.com/managed: "true"
