# Secret used for creating the gitlab_ro_user with the gitlab_ro_user_job.yaml
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitlab-ro-postgresql-password
  namespace: gitlab
spec:
  encryptedData:
    postgresql-gitlab-ro-user-password:
      AgBEqt90PePjr4zMvvFZQ+E5F94XtOiO+5TbiQuJH/eqy8x+xpbeYrnMZvpRgQoRtmGIfAz/1Ql7lhqTe8g5G/QUqdnJu7FHMeTWpH1ZYt5ajikAfyArfwV2FxgqxlfbMJ/fIgHu/5AKAgkpSUkTeOzeT+YN5JsKXwwoc0C2HSZqdjw9Axmfsk62dqksNQIfDXSANk8ZFC4H+ovf5wJZWRF4pHU3DN/JzCSiHlEyTxvZ8Q3Kz0kyfYD2M1m5v689tFfXEV55ck5v0M3GMj8U8Pj1q4lfQm7vQFv+Lli8nVIQcPUc8BfsGVBh50EBWtpE4jFAeug3zNDydrSfo7QFjU5WSwMt6qJEenISQAkG7+ANlprs+4HShgn7T5Dy0wWro7pIWxeLdtxyxaK+uLAvULOI4Ar/WNGAq4c5XV19CqQAbn/utlQ7fhoPW4zU9yQd+L0Y02wKRwghAp/sve0D09AqIgqyWG+n5T6UxWGnRFfPcnbs23bKobmyP+w58P4WFcI3Pq1CUy6Lz77QKVOPfp8aHXWNM8tf1JIbS49j4Bn583xnkDMKflDhlT/0EKe9dKPLW6jceyOQUcrjypj92nmUNAVT/Q5vBG+gksVTtZFa3KQ+wxlgPJaNbT/PgkqugoYp3/BKO0DK//fWHjnpo2gvsWR+fJS9J4UiP8sHk5RW7sUIOt6b8T6p6SY4YuQnMmNvajNepQjpqN+5pVh+QpP8n/0j38aWO1J2oLcYGzraOkyVBE7kpx1224JU8xpm2SdeVP81VqVK90EUCM052VUi
  template:
    metadata:
      annotations:
        kustomize.toolkit.fluxcd.io/reconcile: disabled
        sealedsecrets.bitnami.com/managed: "true"
---
# Secret used for setting up the metabase postgres instance's postgres user
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: metabase-postgresql-password
  namespace: monitoring
spec:
  encryptedData:
    postgresql-password:
      AgB2Z+OYbcCslmb01MbnP5nb0E1GAoDva9sb568cA6QnZw6plTCHiVWSJ5JPpk9Kl3L+tk2pm8oFJR0gcZBkI6JM0vXit0f8a8fjkvy79AdpTU9LTm+N80tGykjlmWJq9yV+v/WHq6/G9e3MREG7OVaCQIr1J++J7hNK7GWtj8UxmmDltrdc5bDPMqQESxB949WX3ONFjjCN+lZoohfl90TltkywnokQktDh+3LCVai9uIr3Gm6vSipvPgLIEMJlENs7c97p90Liz1cN+f56DdWQJvTOzvUD0R88B0bbJl1o0INm45yLjApO3u9T/8fG6snbuEyIAQlJ9ALV7QTMubRrxQKwrlkttmWclEsW2F4Lu5ILFM7FzMEH6pXdhgOr7euiMLr+7FqeaOwMN+Glbz6ihtCt0mIM2ItrxNly3Y23PHrtd/Q87egXYw5tE2aSBFherikDzh2BTpUuBfRLlU2DZYIB99ubwMrLXz3B1Pi8N3TZacPSrbVyEyo4ORVRTI+QkXO9xsFfliTh8mEjO++kgGc4A78cS6S7H/FoiGLhr8mG3JqqTnBCBv0Xyvc3y6xmT4Q8EmIZ+DvlVbJp8X0gOJ2Od+/qQjgfyDb55hoLBjAR9RtE9bptR6sL3vW+z/UUSOalBj0bGwtwOPe9uOPRyc1DmromHx5TdB1nVuj7VYWpChTXXy0CYjmeZF+1Pm8KC+kkEDZfmOijrKhJbMLkWob7GqgjDFFK+hpsHiZIsIJMUhh2wfEFCDgS2A==
  template:
    metadata:
      annotations:
        kustomize.toolkit.fluxcd.io/reconcile: disabled
        sealedsecrets.bitnami.com/managed: "true"
---
# Secret used to log into the GitLab postgres instance
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitlab-postgresql-secrets
  namespace: monitoring
spec:
  encryptedData:
    gitlab-postgresql-host:
      AgBR1BtoZ+VZcRaFWRRyicixJCOEfls5ijerQ0D9kJrTPbw1dZkUkup1u0bgZnN6aK4xXpRajEBbT6o/n7Ub7czzzs9fEzz4DS6GBMZeGf86ObbsOstKBaHkN0JvYh2g917AYbc4zEORFDYnHdQFyiw8R749VGsxSdoGvT8Pkp4n+dpMdvC7nDvHENKURg1k8qNAUSW0NgGQfHH8RjhA3J1gRYBTGZlc7FUHudlDBBGoDNcrFmAy8SCVUWl63eZBUdIhqm7LF0A5T/HZTqoAoqeYJLH+k28ZChDKVZQ9LECx0Mb468xZX8jaeRqbrQ7J8r1gvMYNFeV7yZd4E2975FDjfDnMoRktwuJrXGrc+TFl+UvNB1PBkEDiBc6VUXhNSJnLDFO/xUf4WBMixrmHwXJ3iehCX9goj4FMdC5pgFv/AibuVe6AStNOQyvN3CuW6dBK5N70nluBBcmfy3FQpoH52Mq7TFWd2ml8tpKaRZVcLvDEbQ1yw/Z+a1PxmvIgZulc1D6Q3515jLlI4/WCXv2Yj/p6PivIvn4KfpYKFDNqvC0KpKad0mq8C6fhPACVtpMu7KA8b21CQBQnzoNNbH40VeFd+aipNwHhxspkA4h2hIiPrbCxR7PYFPyUBvKgjuGM7yVNYNkJlYNuanlh1I0hxbkOEWGedWIG5lZjnhBcy234sVUnoDN7JUzcm8la3Csue3EDGr5Y3F447M60WeMzTcW9z+b782YmgFznwjbFQA33QANr3XTCcdtubN0P0gWSNl5gLp5cfmjq
    gitlab-postgresql-password:
      AgABGC5Qp+4EvFtCVMbIqINh6ltOyeauFnOMTACliGBTrXnS+LF6Sm/nT9zozd765zzEW0DQCERyfBKepvn5Ch7qHFdueacpfh8+voPee1Xqv0I1Vn+9N3wBQplhUQCna76/SUMVQGXcoFzILPZFgvvqwKxBkMFCKuIT3yUlhkIDkXjbkVTAxWsViA/15SsKLz3vHZ1niHGpV3J441wvdfCh90LQV8zyEl2IHq7Intq5LgVgZcAQTSQ7KxgdXbr+78dvMivSnr1zkrRyczBQevqeIClKqHg5vbESU31eyt3gL3DnJXi7nRtBgszvJf/1CNKSO69jpf9XOsm0LB2vKLHRnFXCMQQwDWZ9Sv1pxT69VXpiV7LvCKpsoG/zmjC3TctWE30TPwkBDOBF4l7ejXnkiQrSuf0Ix/C4Rav5uIvhrd6sZN/kTQvs1WqkT8w27fvIbbDD5KbNJj/7rfPgA7WIBAV8nZO/JzfCVbv+vn24+cM/PHFi/VYYBlBoD7DW38gxZ3wI0cccNKD6/Ce2veAudoR1kpe/Qse89PPndpTa8R8+bCgJXXkxBpcdwJofNavidinfLTyD/nsgHPsZyw7LuxzIW9cfAks52XWUCD2PLb3TDUdBGlTPlbT9uUUhR6NNW1M/o5G6eHZxaa8okGoEDHM8Ob6JPUANu/8BoeXlDG8JLiAzdwxyLy7QZwp/0H9pS7RSTi3MQu/a7c3ydj/sERYVRA==
  template:
    metadata:
      annotations:
        kustomize.toolkit.fluxcd.io/reconcile: disabled
        sealedsecrets.bitnami.com/managed: "true"
