---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitlab-error-processor
  namespace: custom

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitlab-error-processor
  namespace: custom
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitlab-error-processor
  namespace: custom
subjects:
  - kind: ServiceAccount
    name: gitlab-error-processor
    namespace: custom
roleRef:
  kind: Role
  name: gitlab-error-processor
  apiGroup: rbac.authorization.k8s.io
