---
apiVersion: v1
kind: Service
metadata:
  name: gitlab-error-processor
  namespace: custom
  labels:
    app: gitlab-error-processor
    svc: web
spec:
  type: ClusterIP
  ports:
  - name: web
    port: 80
    targetPort: 8080
  selector:
    app: gitlab-error-processor
    svc: web
