---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: opensearch-index-build-logs
  namespace: custom
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - env:
            - name: OPENSEARCH_ENDPOINT
              valueFrom:
                secretKeyRef:
                  key: opensearch-endpoint
                  name: opensearch-index-build-logs
            - name: OPENSEARCH_USERNAME
              valueFrom:
                secretKeyRef:
                  key: opensearch-username
                  name: opensearch-index-build-logs
            - name: OPENSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: opensearch-password
                  name: opensearch-index-build-logs
            image: ghcr.io/spack/opensearch-index-build-logs:0.0.1
            imagePullPolicy: IfNotPresent
            name: opensearch-index-build-logs
          nodeSelector:
            spack.io/node-pool: base
          restartPolicy: Never
  schedule: 0 0 * * *
