---
apiVersion: v1
data: {}
kind: Secret
metadata:
  annotations:
    fluxcd.io/ignore: 'true'
  labels:
    app.kubernetes.io/instance: karpenter
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: karpenter
    app.kubernetes.io/version: 0.17.0
    helm.sh/chart: karpenter-v0.17.0
  name: karpenter-cert
  namespace: karpenter
