---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::588562868276:role/KarpenterControllerRole-spack
  labels:
    app.kubernetes.io/instance: karpenter
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: karpenter
    app.kubernetes.io/version: 0.17.0
    helm.sh/chart: karpenter-v0.17.0
  name: karpenter
  namespace: karpenter
