---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    fluxcd.io/ignore: 'true'
  labels:
    k8s-app: fluent-bit
  name: fluent-bit-secrets
  namespace: logging
stringData:
  output-elasticsearch.conf: "[OUTPUT]\n    Name             es\n    Match       \
    \     *\n    Host             DEADBEEF  # fake value\n    Port             443\n\
    \    TLS              On\n    AWS_Auth         On\n    AWS_Region       us-east-1\n\
    \    Retry_Limit      6\n    Logstash_Format  On\n    Logstash_Prefix  fluent-bit\n\
    \    Replace_Dots     On\n    Trace_Error      On\n"
type: Opaque
