---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    fluxcd.io/ignore: 'true'
  name: opensearch-index-build-logs
  namespace: custom
stringData:
  opensearch-endpoint: The endpoint of the opensearch API. Should be the same as the
    "host" from k8s/logging/secrets.yaml
  opensearch-password: Password for the admin account of the OpenSearch cluster. Set
    using the AWS console.
  opensearch-username: Admin user name for the OpenSearch cluster. Set using the AWS
    console.
type: Opaque
