---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: karpenter
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: karpenter
    app.kubernetes.io/version: 0.17.0
    helm.sh/chart: karpenter-v0.17.0
  name: karpenter
  namespace: karpenter
spec:
  ports:
  - name: http-metrics
    port: 8080
    protocol: TCP
    targetPort: http-metrics
  - name: https-webhook
    port: 443
    protocol: TCP
    targetPort: https-webhook
  selector:
    app.kubernetes.io/instance: karpenter
    app.kubernetes.io/name: karpenter
  type: ClusterIP
