---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: prune-buildcache-v3
  namespace: custom
spec:
  schedule: "0 0 * * 6"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      activeDeadlineSeconds: 1200 # terminate any running job after 20 minutes
      backoffLimit: 0
      template:
        spec:
          serviceAccountName: prune-buildcache
          restartPolicy: Never
          containers:
          - name: pruner
            # TODO: change image
            image: ghcr.io/mvandenburgh/ci-prune-buildcache:0.0.5
            imagePullPolicy: Always
            resources:
              requests:
                cpu: "16" # 16 cores to allow for high degree of parallelism
                memory: 1G  # based on testing, pruner uses between 500MB and 1GB of memory
              limits:
                memory: 1.5G
            env:
            - name: GITLAB_URL
              value: "https://gitlab.spack.io"
            - name: GITLAB_PROJECT
              value: "spack/spack-packages"
            - name: BUILDCACHE_URL
              value: "s3://spack-binaries/develop"
            - name: PRUNE_REF
              value: "develop"
            - name: PRUNE_SINCE_DAYS
              value: "14"
            envFrom:
              - configMapRef:
                  name: python-scripts-sentry-config
          nodeSelector:
            spack.io/node-pool: beefy
