---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gh-gl-sync
  namespace: custom
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::588562868276:role/DeleteObjectsFromBucketSpackBinariesPRs
