---
# x86_64_v3 runner type: the glr-x86-64-v3 NodePool plus its public and
# protected runners. Everything not set here comes from
# charts/spack-runner-type/values.yaml (including gitlabUrl).
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: runner-x86-v3
  namespace: gitlab
spec:
  interval: 10m
  chart:
    spec:
      chart: ./charts/spack-runner-type
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  dependsOn:
    - name: gitlab
      namespace: gitlab

  valuesFrom:
    # See terraform/modules/spack_aws_k8s/sentry.tf
    - kind: ConfigMap
      name: gitlab-runner-sentry-config
      valuesKey: sentryDsn
      targetPath: public.sentryDsn
    - kind: ConfigMap
      name: gitlab-runner-sentry-config
      valuesKey: sentryDsn
      targetPath: protected.sentryDsn

  values:
    global:
      spack:
        description: x86_64_v3
        nodeLabelKey: spack.io/x86_64
        nodeLabelValue: "v3"
        nodeAffinityComment: Schedule this pod on any node with x86_64 >= v3
        schedulesOn: ["v3", "v4"]
        preferenceComment: x86-64-v3
        nodePreferences:
          - {value: "v3", weight: 2}
          - {value: "v4", weight: 1}
        podAffinityWeight: 4
        nodePool:
          name: glr-x86-64-v3
          arch: amd64
          instanceFamilies:
            - "c4"
            - "c5"
            - "c5a"
            - "c5n"
            - "c6a"
            - "c6i"
            - "m4"
            - "m5"
            - "m5a"
            - "m5n"
            - "m5zn"
            - "m6a"
            - "m6i"
            - "r4"
            - "r5"
            - "r5a"
            - "r5b"
            - "r5n"
            - "r6a"
            - "r6i"
            - "t2"
            - "t3"
            - "t3a"
            - "x1e"
            - "x2iedn"
            - "x2iezn"

    public:
      fullnameOverride: runner-x86-v3-pub-gitlab-runner
      spack:
        cpuLimitMax: "24"
      runners:
        tags: "x86_64,x86_64_v2,x86_64_v3,avx,avx2,small,medium,large,huge,public,aws,spack"

    protected:
      fullnameOverride: runner-x86-v3-prot-gitlab-runner
      spack:
        cpuLimitMax: "32"
      runners:
        tags: "x86_64,x86_64_v2,x86_64_v3,avx,avx2,small,medium,large,huge,protected,aws,spack"
