---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitlab-restart-webservice
  namespace: gitlab
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitlab-restart-webservice
  namespace: gitlab
rules:
  - apiGroups: ["", "extensions", "apps"]
    resources: ["deployments", "replicasets", "pods", "pods/exec"]
    verbs: ["get", "patch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitlab-restart-webservice
  namespace: gitlab
subjects:
  - kind: ServiceAccount
    name: gitlab-restart-webservice
roleRef:
  kind: Role
  name: gitlab-restart-webservice
  apiGroup: rbac.authorization.k8s.io
