---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rotate-keys
  namespace: custom
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::588562868276:role/RotateIAMAccessKeysForGitLab
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: clear-admin-keys
  namespace: custom
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::588562868276:role/ClearAdministratorsIAMAccessKeys
