apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../production/custom/gh-gl-sync/cron-jobs.yaml
patches:
  - target:
      kind: CronJob
      name: gh-gl-sync
      namespace: custom
    patch: |-
      - op: replace
        path: /spec/jobTemplate/spec/template/spec/containers/0/args
        value:
          - "mvandenburgh/spack"
          - "ssh://git@ssh.gitlab.staging.spack.io/spack/spack"
          - "https://gitlab.staging.spack.io"
          - "spack/spack"
          - "--pr-mirror-bucket"
          - "spack-binaries-prs-staging"
          - "--main-branch"
          - "develop"
          - "--prereq-check"
          - "prechecks / style"
