---
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: x86-64-v2-win
spec:
  template:
    metadata:
      # Label all provisioned nodes with pipeline/arch/os specifiers
      labels:
        spack.io/pipeline: "true"
        spack.io/x86_64: "v2" # highest supported x86_64 microarch version
        spack.io/os: "windows"

    spec:
      requirements:
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]
        - key: kubernetes.io/os
          operator: In
          values: ["windows"]
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: "karpenter.k8s.aws/instance-family"
          operator: In
          values:
            - "m5"
        - key: "karpenter.k8s.aws/instance-size"
          operator: In
          values:
            - "2xlarge"
        - key: "topology.kubernetes.io/zone"
          operator: In
          values:
            - "us-east-1a"
            - "us-east-1b"
            - "us-east-1c"
            - "us-east-1d"

      nodeClassRef:
        apiVersion: karpenter.k8s.aws/v1beta1
        kind: EC2NodeClass
        name: windows

      taints:
        # Taint windows nodes to ensure pods must explicitly "opt-in" to be scheduled on them.
        - key: "windows"
          value: "true"
          effect: NoSchedule
        # Taint these nodes so only pipeline pods will be scheduled on them.
        - key: spack.io/runner-taint
          value: "true"
          effect: NoSchedule

  limits:
    cpu: 3840 # 16 vCPUs * 6 replicas * 20 concurrent jobs * 2 runners (public & protected)
    memory: 15Ti # 64 Gi * 6 replicas * 20 concurrent jobs * 2 runners (public & protected)

  # Wait 2 hours before deprovisioning a Windows runner pod.
  # This is due to the long startup time Windows nodes have.
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 7200s
