---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: stuckpod-controller
  namespace: custom

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: stuckpod-controller
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list", "update", "create", "patch", "delete"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: stuckpod-controller
subjects:
  - kind: ServiceAccount
    name: stuckpod-controller
    namespace: custom
roleRef:
  kind: ClusterRole
  name: stuckpod-controller
  apiGroup: rbac.authorization.k8s.io
