---
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-secrets
  namespace: gitlab
  annotations:
    fluxcd.io/ignore: "true"
stringData:
  values.yaml: |
    global:
      psql:
        host: host.rds.example.com # fake hostname
  postgres-password: password # fake password
  gitlabToken: token # fake token
