# This patch removes the SealedSecret with signing key info,
# as we don't need it for staging.
$patch: delete
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: spack-intermediate-ci-signing-key
  namespace: pipeline
