---
# Provisioner for gitlab pods
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: gitlab
spec:
  template:
    metadata:
      # Only provision nodes for pods specifying the gitlab node pool
      labels:
        spack.io/node-pool: gitlab
    spec:
      requirements:
        # Always use amd64 nodes
        - key: "kubernetes.io/arch"
          operator: In
          values: ["amd64"]

        # Always use on-demand
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: ["on-demand"]

        # Only provision nodes for Linux pods
        # Needed due to https://github.com/kubernetes-sigs/karpenter/issues/1009
        - key: "kubernetes.io/os"
          operator: In
          values: ["linux"]

      nodeClassRef:
        apiVersion: karpenter.k8s.aws/v1beta1
        kind: EC2NodeClass
        name: default

  # Terminate nodes after 5 minutes of idle time
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 5m
