apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: fluent-bit-secrets
  namespace: fluent-bit
spec:
  encryptedData:
    output-elasticsearch.conf: AgAeahr8KkJlanXjAN2xRwwpdDOEtOdhNe8LkJvo8zAlOK1pE5lIBH7CpgVkx/eLn+KUhdxReU/j2eh23FqaUKElgOB8RMrlorYAuCuP1pESD9GNCA1jl9DxMJtZ2+/KSvinZoC06coQXGD6a5fTbfXEMp8Y8XDoWTNv7Zdp8VrQ986V5sNcMi3f3R4FnkyvzcKSBFzbTpHVrebj4TjnZh6C4xiL6LvGTo2T4+hwXajfLTALGn/EOznbWLxlQYZCU/n2MX+rx98jeqWJ7VAGBL3O8/7crn3GzC8OEZ2rJ4S+nGzhgb9dmvHsTwfLnWNegGREMbmvlKyRNr6FUYhN4YMSe7CWTiTO6W/zNqXhqKIQAHYeFR8TBTtKEADdE/Wx+RJD8p1WHm8vL4qSnuczHgBow4GWkM5wqIuCzfbXlarKazAK0ehkRRzLJnHJa6Jy9JBzSDt00ug9W+BTMdmCFRstu8i7ZLB7hs8k+/pSj2E61QoqUAaU/PmRzrTpDJ11dGAuMWGPlM5KMp/7sMhah4bltjoZ7p2iT9Jxz0PPg1K6O3nPKwaAeGFyClfvMKrnbf6iLYNgtaEjKWCxMU/NILy1WdX2RyGKhLSe+l4LTLKVaVNnl4ctwl9Mcni7n9rrmWHS69dtH93owGJoowATIXfup8TNTcioq6uDNnRfQLVQx7veI83ipLlt+aBRwlOK6jdWj84pxnXDD87D1o+HEtU50QEqOtC56xMpCOdTrj0itJzIVdN9wV7A4U3d+hzbowfOX5qWQgKD37rrzU/HH7n6XMU6e/V3UO1zK2LdM5qAeNToMUaOt7C1C7M5Fnfee4+5kDCp7nk71ERTSgxrmAww42Q6lCk3bSqPF1iIoqBqPrpiirhOEn5KuHV1VwqLpza3HSlFU3hXC+9V48+vVPkVYk2AQMnGWbY9sSO4R4/NxADpmbzltaXsN216mYxxzGmqx59t83B1Crtw7LiFotS4RkWqO8IIet/tU3GQoxtxCgz3umY6gjNm91vmdWvwY0aOlzko6ToGwJQLYFnut77OqRLaLqe/3zW41cuPFnOsZFGXiHcvMWCpeFQpj0vAGSqEJN5mx1r6fVxzEB3GaAWDf+U9QLnKPQIYUnN2Oex/zalMPCTZs0mwTKWTjzpNw7k1OHRmP0g9gDK8EdpLRDr+pxYlwpGlfWTJt1XX8yRdfcgdIfkI1ow=
  template:
    metadata:
      annotations:
        kustomize.toolkit.fluxcd.io/reconcile: disabled
        sealedsecrets.bitnami.com/managed: "true"
      labels:
        k8s-app: fluent-bit
