apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: webhook-handler-pre-deploy
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./pre-deploy/"
  interval: 5m
  timeout: 5m
  prune: true
  wait: true
  force: true
