---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: gitlab
  namespace: gitlab
spec:
  releaseName: gitlab
  chart:
    name: gitlab
    repository: https://charts.gitlab.io
    version: 5.6.3 # gitlab@14.6.3

  valuesFrom:
    - secretKeyRef:
        name: gitlab-secrets
        namespace: gitlab
        key: values.yaml
        optional: false

  values:
    nodeSelector:
      spack.io/node-pool: gitlab

    global:
      common:
        labels: {}

      operator:
        enabled: false

      edition: ee

      hosts:
        domain: spack.io
        https: true
        gitlab:
          name: gitlab.spack.io
        minio:
          name: minio.gitlab.spack.io
        registry:
          name: registry.gitlab.spack.io
        smartcard:
          enabled: false
        ssh: ssh.gitlab.spack.io

      ingress:
        configureCertmanager: false
        class: nginx

      gitlab:
        license: {}

      initialRootPassword: {}

      email:
        from: admin@gitlab.spack.io
        reply_to: noreply@gitlab.spack.io
      smtp:
        enabled: true
        address: email-smtp.us-east-1.amazonaws.com
        user_name: AKIAYSCIUVA2L2NKBRON
        password:
          secret: gitlab-secrets
          key: smtp-password
        port: 465
        tls: true

      psql:
        connectTimeout:
        password:
          secret: gitlab-secrets
          key: postgres-password
        port: 5432
        database: gitlabhq_production
        username: postgres

      redis:
        password:
          enabled: true

      minio:
        enabled: true

      grafana:
        enabled: false

      appConfig:
        smartcard:
          enabled: false

      antiAffinity: hard
    ### END OF GLOBAL SECTION

    certmanager:
      install: false

    prometheus:
      install: false

    nginx-ingress:
      enabled: false

    minio:
      ingress:
        tls:
          secretName: tls-gitlab-minio
      nodeSelector:
        spack.io/node-pool: gitlab
      persistence:
        size: 1000Gi
      resources:
        requests:
          cpu: 200m
          memory: 12G

    registry:
      ingress:
        tls:
          secretName: tls-gitlab-registry
      nodeSelector:
        spack.io/node-pool: gitlab

    gitlab-runner:
      install: false

    gitlab:
      ingress:
        tls:
          enabled: true
      webservice:
        ingress:
          enabled: true
          tls:
            enabled: true
            secretName: tls-gitlab-webservice
        image:
          pullPolicy: IfNotPresent
          repository: ghcr.io/spack/gitlab-webservice
          tag: v14.6.3
        minReplicas: 4
        maxReplicas: 16
        resources:
          limits:
            cpu: 1500m
            memory: 3.5G
          requests:
            cpu: 300m
            memory: 2.5G
        nodeSelector:
          spack.io/node-pool: gitlab
      gitlab-exporter:
        nodeSelector:
          spack.io/node-pool: gitlab

      gitlab-shell:
        service:
          type: LoadBalancer
        nodeSelector:
          spack.io/node-pool: gitlab

      sidekiq:
        image:
          pullPolicy: IfNotPresent
          repository: ghcr.io/spack/gitlab-sidekiq
          tag: v14.6.3
        nodeSelector:
          spack.io/node-pool: gitlab

      toolbox:
        image:
          pullPolicy: IfNotPresent
          repository: ghcr.io/spack/gitlab-toolbox
          tag: v14.6.3
        nodeSelector:
          spack.io/node-pool: gitlab

        replicas: 8
        antiAffinityLabels:
          matchLabels:
            app: 'gitaly'

      gitaly:
        nodeSelector:
          spack.io/node-pool: gitlab

      migrations:
        nodeSelector:
          spack.io/node-pool: gitlab

    postgresql:
      install: false
