apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../production/custom/namespace.yaml
- ../../production/custom/gitlab-error-processor/deployments.yaml
- ../../production/custom/gitlab-error-processor/services.yaml
- ../../production/custom/gitlab-error-processor/service-accounts.yaml
- ../../production/custom/gitlab-api-scrape/cron-jobs.yaml
- ../../production/custom/gitlab-api-scrape/service-accounts.yaml
- ../../production/custom/node-share-controller/config-maps.yaml
- ../../production/custom/node-share-controller/service-accounts.yaml
- ../../production/custom/node-share-controller/deployment.yaml
- ../../production/custom/gh-gl-sync/cron-jobs.yaml
- ../../production/custom/gh-gl-sync/service-accounts.yaml
- ../../production/custom/rotate-keys/cron-jobs.yaml
- ../../production/custom/rotate-keys/service-accounts.yaml
- ../../production/custom/unstick-pipelines/cron-jobs.yaml
- ../../production/custom/gitlab-stuckpods/service-accounts.yaml
- ../../production/custom/gitlab-stuckpods/deployment.yaml
- ../../production/custom/skipped-pipelines/cron-jobs.yaml
- ../../production/custom/opensearch-index-build-logs/cron-jobs.yaml
patches:
  - target:
      kind: CronJob
      name: gh-gl-sync
      namespace: custom
    patch: |-
      - op: replace
        path: /spec/jobTemplate/spec/template/spec/containers/0/args
        value:
          - "spack-test/spack"
          - "ssh://git@ssh.gitlab.staging.spack.io/spack/spack"
          - "https://gitlab.staging.spack.io"
          - "spack/spack"
          - "--main-branch"
          - "develop"
          - "--prereq-check"
          - "prechecks / style"
