apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drift-server-db
  namespace: spack
  labels:
    app: drift-server-spack-io
    svc: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
