# apiVersion: monitoring.coreos.com/v1
# kind: ServiceMonitor
# metadata:
#   name: karpenter
#   namespace: monitoring
#   labels:
#     release: kube-prometheus-stack
# spec:
#   selector:
#     matchLabels:
#       app.kubernetes.io/name: karpenter
#   endpoints:
#     - port: http-metrics
#   namespaceSelector:
#     matchNames: ["karpenter"]
