---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: metabase-postgresql
  namespace: monitoring
  annotations:
    kustomize.toolkit.fluxcd.io/reconcile: disabled
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
