name: Check Analytics Migrations

on:
  pull_request:
    paths:
      - "analytics/**"

jobs:
  check-migrations:
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: django
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
      elasticsearch:
        image: elasticsearch:7.14.0
        env:
          ES_JAVA_OPTS: "-Xms250m -Xmx750m"
          discovery.type: single-node
          xpack.security.enabled: "true"
          ELASTIC_PASSWORD: elastic
        ports:
          - 9200:9200
      redis:
        image: redis:latest
        ports:
          - 6379:6379

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install requirements
        run: pip install -r ./analytics/requirements.txt

      - name: Provide default env vars for django
        run: cat ./analytics/dev/.env.docker-compose >> $GITHUB_ENV

      # This runs on pull requests and blocks until any necessary migrations have been created
      - name: Check for Migrations
        run: ./analytics/manage.py makemigrations --check --noinput
