name: Validate Terraform

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  validate_terraform:
    name: Validate Terraform
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        directory: [terraform, terraform-bootstrap]
        environment: [production, staging]
    defaults:
      run:
        working-directory: ${{ matrix.directory }}/${{ matrix.environment }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.3.7

    - run: terraform init -backend=false

    - run: terraform fmt -check

    - run: terraform validate
