name: gitops

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  validate-fmt:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        environment: [production, staging]
        directory: [terraform, terraform-bootstrap]
    defaults:
      run:
        working-directory: ${{ matrix.directory }}/${{ matrix.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init -backend=false

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

  plan:
    needs: validate-fmt
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - environment: production
            aws-region: us-east-1
          - environment: staging
            aws-region: us-west-1
    defaults:
      run:
        working-directory: terraform/${{ matrix.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::588562868276:role/GitHubActionsRole-${{ matrix.environment }}
          aws-region: ${{ matrix.aws-region }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Plan
        run: terraform plan
