name: Validate staging JSON patches

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  validate:
    name: Validate staging JSON patch YAMLs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install PyYAML

    - name: Run staging patch validation script
      run: python scripts/validate_staging_patches.py
