# apiVersion: bitnami.com/v1alpha1
# kind: SealedSecret
# metadata:
#   name: mysecret
#   namespace: mynamespace
#   # Annotations on the SealedSecret resource, not the unsealed Secret resource
#   annotations:
#     foo: bar
# spec:
#   encryptedData:
#     foo: bar
#   template:
#     # This is an example of labels and annotations that will be added to the output secret
#     metadata:
#       labels:
#         foo: bar
#       annotations:
#         foo: bar
